[
    { id: 3101, word: "Seek", meaning: "Aramak", level: "B2" },
    { id: 3102, word: "Seem", meaning: "Görünmek", level: "A2" },
    { id: 3103, word: "Segment", meaning: "Segment, Parça", level: "B2" },
    { id: 3104, word: "Select", meaning: "Seçmek", level: "A2" },
    { id: 3105, word: "Selection", meaning: "Seçim", level: "B1" },
    { id: 3106, word: "Self", meaning: "Kendi", level: "B2" },
    { id: 3107, word: "Sell", meaning: "Satmak", level: "A2" },
    { id: 3108, word: "Seller", meaning: "Satıcı", level: "A2" },
    { id: 3109, word: "Semi", meaning: "Yarı", level: "B1" },
    { id: 3110, word: "Senate", meaning: "Senato", level: "B2" },
    { id: 3111, word: "Senator", meaning: "Senatör", level: "B2" },
    { id: 3112, word: "Send", meaning: "Göndermek", level: "A2" },
    { id: 3113, word: "Senior", meaning: "Kıdemli", level: "B2" },
    { id: 3114, word: "Sense", meaning: "Duyu, Mantık", level: "B1" },
    { id: 3115, word: "Sensible", meaning: "Mantıklı", level: "B1" },
    { id: 3116, word: "Sensitive", meaning: "Hassas", level: "B1" },
    { id: 3117, word: "Sentence", meaning: "Cümle", level: "A2" },
    { id: 3118, word: "Separate", meaning: "Ayırmak", level: "B1" },
    { id: 3119, word: "Separately", meaning: "Ayrı ayrı", level: "B1" },
    { id: 3120, word: "Separation", meaning: "Ayrılık", level: "B2" },
    { id: 3121, word: "September", meaning: "Eylül", level: "A2" },
    { id: 3122, word: "Sequence", meaning: "Dizi, Sıra", level: "B2" },
    { id: 3123, word: "Series", meaning: "Seri", level: "B1" },
    { id: 3124, word: "Serious", meaning: "Ciddi", level: "A2" },
    { id: 3125, word: "Seriously", meaning: "Ciddiyetle", level: "A2" },
    { id: 3126, word: "Servant", meaning: "Hizmetçi", level: "B1" },
    { id: 3127, word: "Serve", meaning: "Hizmet etmek", level: "A2" },
    { id: 3128, word: "Service", meaning: "Servis, Hizmet", level: "A2" },
    { id: 3129, word: "Session", meaning: "Oturum", level: "B2" },
    { id: 3130, word: "Set", meaning: "Ayarlamak, Set", level: "A2" },
    { id: 3131, word: "Setting", meaning: "Ayar", level: "B1" },
    { id: 3132, word: "Settle", meaning: "Yerleşmek, Çözmek", level: "B2" },
    { id: 3133, word: "Settlement", meaning: "Yerleşim", level: "B2" },
    { id: 3134, word: "Seven", meaning: "Yedi", level: "A2" },
    { id: 3135, word: "Seventeen", meaning: "On yedi", level: "A2" },
    { id: 3136, word: "Seventy", meaning: "Yetmiş", level: "A2" },
    { id: 3137, word: "Several", meaning: "Birkaç", level: "A2" },
    { id: 3138, word: "Severe", meaning: "Ağır, Şiddetli", level: "B2" },
    { id: 3139, word: "Sew", meaning: "Dikmek", level: "B1" },
    { id: 3140, word: "Sex", meaning: "Cinsiyet", level: "B1" },
    { id: 3141, word: "Sexual", meaning: "Cinsel", level: "B2" },
    { id: 3142, word: "Shade", meaning: "Gölge", level: "B1" },
    { id: 3143, word: "Shadow", meaning: "Gölge", level: "B1" },
    { id: 3144, word: "Shake", meaning: "Sallamak", level: "A2" },
    { id: 3145, word: "Shall", meaning: "-ecek, -acak", level: "A2" },
    { id: 3146, word: "Shallow", meaning: "Sığ", level: "B2" },
    { id: 3147, word: "Shame", meaning: "Utanç", level: "B1" },
    { id: 3148, word: "Shape", meaning: "Şekil", level: "A2" },
    { id: 3149, word: "Share", meaning: "Paylaşmak", level: "A2" },
    { id: 3150, word: "Sharp", meaning: "Keskin", level: "B1" },
    { id: 3151, word: "She", meaning: "O (Kadın)", level: "A2" },
    { id: 3152, word: "Sheep", meaning: "Koyun", level: "A2" },
    { id: 3153, word: "Sheet", meaning: "Çarşaf, Kağıt", level: "B1" },
    { id: 3154, word: "Shelf", meaning: "Raf", level: "A2" },
    { id: 3155, word: "Shell", meaning: "Kabuk", level: "B1" },
    { id: 3156, word: "Shelter", meaning: "Barınak", level: "B2" },
    { id: 3157, word: "Shift", meaning: "Vardiya, Kaydırmak", level: "B1" },
    { id: 3158, word: "Shine", meaning: "Parlamak", level: "B1" },
    { id: 3159, word: "Shiny", meaning: "Parlak", level: "B1" },
    { id: 3160, word: "Ship", meaning: "Gemi", level: "A2" },
    { id: 3161, word: "Shirt", meaning: "Gömlek", level: "A2" },
    { id: 3162, word: "Shock", meaning: "Şok", level: "B1" },
    { id: 3163, word: "Shocked", meaning: "Şok olmuş", level: "B1" },
    { id: 3164, word: "Shocking", meaning: "Şok edici", level: "B1" },
    { id: 3165, word: "Shoe", meaning: "Ayakkabı", level: "A2" },
    { id: 3166, word: "Shoot", meaning: "Ateş etmek", level: "B1" },
    { id: 3167, word: "Shooting", meaning: "Atış", level: "B2" },
    { id: 3168, word: "Shop", meaning: "Mağaza", level: "A2" },
    { id: 3169, word: "Shopping", meaning: "Alışveriş", level: "A2" },
    { id: 3170, word: "Shore", meaning: "Kıyı", level: "B1" },
    { id: 3171, word: "Short", meaning: "Kısa", level: "A2" },
    { id: 3172, word: "Shortly", meaning: "Kısa süre sonra", level: "B1" },
    { id: 3173, word: "Shot", meaning: "Atış, Şut", level: "B1" },
    { id: 3174, word: "Should", meaning: "-meli, -malı", level: "A2" },
    { id: 3175, word: "Shoulder", meaning: "Omuz", level: "A2" },
    { id: 3176, word: "Shout", meaning: "Bağırmak", level: "A2" },
    { id: 3177, word: "Show", meaning: "Göstermek", level: "A2" },
    { id: 3178, word: "Shower", meaning: "Duş", level: "A2" },
    { id: 3179, word: "Shut", meaning: "Kapatmak", level: "A2" },
    { id: 3180, word: "Shy", meaning: "Utangaç", level: "B1" },
    { id: 3181, word: "Sick", meaning: "Hasta", level: "A2" },
    { id: 3182, word: "Side", meaning: "Yan", level: "A2" },
    { id: 3183, word: "Sight", meaning: "Görüş", level: "B1" },
    { id: 3184, word: "Sign", meaning: "İmza, Tabela", level: "A2" },
    { id: 3185, word: "Signal", meaning: "Sinyal", level: "B1" },
    { id: 3186, word: "Signature", meaning: "İmza", level: "B1" },
    { id: 3187, word: "Significance", meaning: "Önem", level: "B2" },
    { id: 3188, word: "Significant", meaning: "Önemli", level: "B1" },
    { id: 3189, word: "Significantly", meaning: "Önemli ölçüde", level: "B2" },
    { id: 3190, word: "Silence", meaning: "Sessizlik", level: "B1" },
    { id: 3191, word: "Silent", meaning: "Sessiz", level: "B1" },
    { id: 3192, word: "Silk", meaning: "İpek", level: "B1" },
    { id: 3193, word: "Silly", meaning: "Aptalca", level: "A2" },
    { id: 3194, word: "Silver", meaning: "Gümüş", level: "A2" },
    { id: 3195, word: "Similar", meaning: "Benzer", level: "A2" },
    { id: 3196, word: "Similarity", meaning: "Benzerlik", level: "B1" },
    { id: 3197, word: "Similarly", meaning: "Benzer şekilde", level: "B1" },
    { id: 3198, word: "Simple", meaning: "Basit", level: "A2" },
    { id: 3199, word: "Simply", meaning: "Basitçe", level: "B1" },
    { id: 3200, word: "Since", meaning: "-den beri", level: "A2" },
    { id: 3201, word: "Sincere", meaning: "Samimi", level: "B2" },
    { id: 3202, word: "Sing", meaning: "Şarkı söylemek", level: "A2" },
    { id: 3203, word: "Singer", meaning: "Şarkıcı", level: "A2" },
    { id: 3204, word: "Singing", meaning: "Şarkı söyleme", level: "A2" },
    { id: 3205, word: "Single", meaning: "Tek, Bekar", level: "A2" },
    { id: 3206, word: "Sink", meaning: "Lavabo, Batmak", level: "B1" },
    { id: 3207, word: "Sir", meaning: "Bayım, Efendim", level: "A2" },
    { id: 3208, word: "Sister", meaning: "Kız kardeş", level: "A2" },
    { id: 3209, word: "Sit", meaning: "Oturmak", level: "A2" },
    { id: 3210, word: "Site", meaning: "Site, Yer", level: "A2" },
    { id: 3211, word: "Situation", meaning: "Durum", level: "A2" },
    { id: 3212, word: "Six", meaning: "Altı", level: "A2" },
    { id: 3213, word: "Sixteen", meaning: "On altı", level: "A2" },
    { id: 3214, word: "Sixty", meaning: "Altmış", level: "A2" },
    { id: 3215, word: "Size", meaning: "Boyut", level: "A2" },
    { id: 3216, word: "Skill", meaning: "Beceri", level: "A2" },
    { id: 3217, word: "Skilled", meaning: "Becerikli", level: "B1" },
    { id: 3218, word: "Skin", meaning: "Cilt", level: "A2" },
    { id: 3219, word: "Skirt", meaning: "Etek", level: "A2" },
    { id: 3220, word: "Sky", meaning: "Gökyüzü", level: "A2" },
    { id: 3221, word: "Sleep", meaning: "Uyumak", level: "A2" },
    { id: 3222, word: "Sleeve", meaning: "Kol (elbise)", level: "B2" },
    { id: 3223, word: "Slice", meaning: "Dilim", level: "B1" },
    { id: 3224, word: "Slide", meaning: "Slayt, Kaymak", level: "B2" },
    { id: 3225, word: "Slight", meaning: "Hafif", level: "B1" },
    { id: 3226, word: "Slightly", meaning: "Hafifçe", level: "B1" },
    { id: 3227, word: "Slim", meaning: "İnce", level: "B1" },
    { id: 3228, word: "Slip", meaning: "Kaymak", level: "B2" },
    { id: 3229, word: "Slow", meaning: "Yavaş", level: "A2" },
    { id: 3230, word: "Slowly", meaning: "Yavaşça", level: "A2" },
    { id: 3231, word: "Small", meaning: "Küçük", level: "A2" },
    { id: 3232, word: "Smart", meaning: "Zeki, Şık", level: "A2" },
    { id: 3233, word: "Smell", meaning: "Koklamak, Koku", level: "A2" },
    { id: 3234, word: "Smile", meaning: "Gülümsemek", level: "A2" },
    { id: 3235, word: "Smoke", meaning: "Sigara içmek, Duman", level: "A2" },
    { id: 3236, word: "Smoking", meaning: "Sigara içme", level: "A2" },
    { id: 3237, word: "Smooth", meaning: "Pürüzsüz", level: "B1" },
    { id: 3238, word: "Snake", meaning: "Yılan", level: "A2" },
    { id: 3239, word: "Snow", meaning: "Kar", level: "A2" },
    { id: 3240, word: "So", meaning: "Öyleyse, Bu yüzden", level: "A2" },
    { id: 3241, word: "Soap", meaning: "Sabun", level: "A2" },
    { id: 3242, word: "Soccer", meaning: "Futbol", level: "A2" },
    { id: 3243, word: "Social", meaning: "Sosyal", level: "A2" },
    { id: 3244, word: "Society", meaning: "Toplum", level: "B1" },
    { id: 3245, word: "Sock", meaning: "Çorap", level: "A2" },
    { id: 3246, word: "Soft", meaning: "Yumuşak", level: "A2" },
    { id: 3247, word: "Software", meaning: "Yazılım", level: "B1" },
    { id: 3248, word: "Soil", meaning: "Toprak", level: "B1" },
    { id: 3249, word: "Soldier", meaning: "Asker", level: "A2" },
    { id: 3250, word: "Solid", meaning: "Katı", level: "B1" },
    { id: 3251, word: "Solution", meaning: "Çözüm", level: "B1" },
    { id: 3252, word: "Solve", meaning: "Çözmek", level: "A2" },
    { id: 3253, word: "Some", meaning: "Bazı", level: "A2" },
    { id: 3254, word: "Somebody", meaning: "Birisi", level: "A2" },
    { id: 3255, word: "Someone", meaning: "Birisi", level: "A2" },
    { id: 3256, word: "Something", meaning: "Bir şey", level: "A2" },
    { id: 3257, word: "Sometimes", meaning: "Bazen", level: "A2" },
    { id: 3258, word: "Somewhere", meaning: "Bir yerlerde", level: "A2" },
    { id: 3259, word: "Son", meaning: "Oğul", level: "A2" },
    { id: 3260, word: "Song", meaning: "Şarkı", level: "A2" },
    { id: 3261, word: "Soon", meaning: "Yakında", level: "A2" },
    { id: 3262, word: "Sore", meaning: "Ağrılı", level: "B1" },
    { id: 3263, word: "Sorry", meaning: "Üzgün", level: "A2" },
    { id: 3264, word: "Sort", meaning: "Tür", level: "A2" },
    { id: 3265, word: "Soul", meaning: "Ruh", level: "B2" },
    { id: 3266, word: "Sound", meaning: "Ses", level: "A2" },
    { id: 3267, word: "Soup", meaning: "Çorba", level: "A2" },
    { id: 3268, word: "Sour", meaning: "Ekşi", level: "B1" },
    { id: 3269, word: "South", meaning: "Güney", level: "A2" },
    { id: 3270, word: "Southern", meaning: "Güneyli", level: "B1" },
    { id: 3271, word: "Space", meaning: "Uzay, Boşluk", level: "A2" },
    { id: 3272, word: "Spare", meaning: "Yedek", level: "B1" },
    { id: 3273, word: "Speak", meaning: "Konuşmak", level: "A2" },
    { id: 3274, word: "Speaker", meaning: "Hoparlör, Konuşmacı", level: "A2" },
    { id: 3275, word: "Special", meaning: "Özel", level: "A2" },
    { id: 3276, word: "Specialist", meaning: "Uzman", level: "B2" },
    { id: 3277, word: "Specialize", meaning: "Uzmanlaşmak", level: "B2" },
    { id: 3278, word: "Species", meaning: "Türler", level: "B2" },
    { id: 3279, word: "Specific", meaning: "Belirli", level: "B1" },
    { id: 3280, word: "Specifically", meaning: "Özellikle", level: "B2" },
    { id: 3281, word: "Speech", meaning: "Konuşma", level: "B1" },
    { id: 3282, word: "Speed", meaning: "Hız", level: "A2" },
    { id: 3283, word: "Spell", meaning: "Hecelemek", level: "A2" },
    { id: 3284, word: "Spelling", meaning: "Yazım", level: "A2" },
    { id: 3285, word: "Spend", meaning: "Harcamak", level: "A2" },
    { id: 3286, word: "Spice", meaning: "Baharat", level: "B1" },
    { id: 3287, word: "Spicy", meaning: "Baharatlı", level: "B1" },
    { id: 3288, word: "Spider", meaning: "Örümcek", level: "A2" },
    { id: 3289, word: "Spin", meaning: "Dönmek", level: "B1" },
    { id: 3290, word: "Spirit", meaning: "Ruh, İspirto", level: "B1" },
    { id: 3291, word: "Spiritual", meaning: "Manevi", level: "B2" },
    { id: 3292, word: "Split", meaning: "Bölmek", level: "B2" },
    { id: 3293, word: "Spoon", meaning: "Kaşık", level: "A2" },
    { id: 3294, word: "Sport", meaning: "Spor", level: "A2" },
    { id: 3295, word: "Spot", meaning: "Nokta, Yer", level: "B2" },
    { id: 3296, word: "Spread", meaning: "Yaymak", level: "B1" },
    { id: 3297, word: "Spring", meaning: "Bahar, Yay", level: "A2" },
    { id: 3298, word: "Square", meaning: "Kare, Meydan", level: "A2" },
    { id: 3299, word: "Stable", meaning: "İstikrarlı, Ahır", level: "B2" },
    { id: 3300, word: "Staff", meaning: "Personel", level: "B1" },
    { id: 3301, word: "Stage", meaning: "Aşama, Sahne", level: "A2" },
    { id: 3302, word: "Stair", meaning: "Basamak, Merdiven", level: "A2" },
    { id: 3303, word: "Stamp", meaning: "Pul, Damga", level: "A2" },
    { id: 3304, word: "Stand", meaning: "Ayakta durmak", level: "A2" },
    { id: 3305, word: "Standard", meaning: "Standart", level: "B1" },
    { id: 3306, word: "Star", meaning: "Yıldız", level: "A2" },
    { id: 3307, word: "Stare", meaning: "Bakakalmak", level: "B2" },
    { id: 3308, word: "Start", meaning: "Başlamak", level: "A2" },
    { id: 3309, word: "State", meaning: "Devlet, Durum", level: "B1" },
    { id: 3310, word: "Statement", meaning: "İfade, Beyan", level: "B1" },
    { id: 3311, word: "Station", meaning: "İstasyon", level: "A2" },
    { id: 3312, word: "Statistic", meaning: "İstatistik", level: "B2" },
    { id: 3313, word: "Status", meaning: "Statü", level: "B2" },
    { id: 3314, word: "Stay", meaning: "Kalmak", level: "A2" },
    { id: 3315, word: "Steady", meaning: "İstikrarlı", level: "B2" },
    { id: 3316, word: "Steak", meaning: "Biftek", level: "A2" },
    { id: 3317, word: "Steal", meaning: "Çalmak", level: "A2" },
    { id: 3318, word: "Steam", meaning: "Buhar", level: "B1" },
    { id: 3319, word: "Steel", meaning: "Çelik", level: "B2" },
    { id: 3320, word: "Step", meaning: "Adım", level: "A2" },
    { id: 3321, word: "Stick", meaning: "Sopa, Yapıştırmak", level: "B1" },
    { id: 3322, word: "Sticky", meaning: "Yapışkan", level: "B1" },
    { id: 3323, word: "Stiff", meaning: "Sert", level: "B2" },
    { id: 3324, word: "Still", meaning: "Hala", level: "A2" },
    { id: 3325, word: "Stimulate", meaning: "Uykulandıran, Uyarmak", level: "C1" },
    { id: 3326, word: "Stomach", meaning: "Mide", level: "A2" },
    { id: 3327, word: "Stone", meaning: "Taş", level: "A2" },
    { id: 3328, word: "Stop", meaning: "Durmak", level: "A2" },
    { id: 3329, word: "Store", meaning: "Dükkan, Depolamak", level: "A2" },
    { id: 3330, word: "Storm", meaning: "Fırtına", level: "A2" },
    { id: 3331, word: "Story", meaning: "Hikaye", level: "A2" },
    { id: 3332, word: "Straight", meaning: "Düz", level: "A2" },
    { id: 3333, word: "Strange", meaning: "Garip", level: "A2" },
    { id: 3334, word: "Stranger", meaning: "Yabancı", level: "B1" },
    { id: 3335, word: "Strategy", meaning: "Strateji", level: "B1" },
    { id: 3336, word: "Stream", meaning: "Dere, Akış", level: "B2" },
    { id: 3337, word: "Street", meaning: "Sokak", level: "A2" },
    { id: 3338, word: "Strength", meaning: "Güç", level: "B1" },
    { id: 3339, word: "Stress", meaning: "Stres", level: "B1" },
    { id: 3340, word: "Stressed", meaning: "Stresli", level: "B1" },
    { id: 3341, word: "Stretch", meaning: "Uzatmak", level: "B2" },
    { id: 3342, word: "Strict", meaning: "Sert, Katı", level: "B2" },
    { id: 3343, word: "Strike", meaning: "Grev, Vurmak", level: "B1" },
    { id: 3344, word: "String", meaning: "İp, Tel", level: "B1" },
    { id: 3345, word: "Strong", meaning: "Güçlü", level: "A2" },
    { id: 3346, word: "Strongly", meaning: "Güçlü bir şekilde", level: "B1" },
    { id: 3347, word: "Structure", meaning: "Yapı", level: "B1" },
    { id: 3348, word: "Struggle", meaning: "Çabalamak", level: "B2" },
    { id: 3349, word: "Student", meaning: "Öğrenci", level: "A2" },
    { id: 3350, word: "Studio", meaning: "Stüdyo", level: "B1" },
    { id: 3351, word: "Study", meaning: "Çalışmak", level: "A2" },
    { id: 3352, word: "Stuff", meaning: "Şeyler", level: "B1" },
    { id: 3353, word: "Stupid", meaning: "Aptal", level: "A2" },
    { id: 3354, word: "Style", meaning: "Stil", level: "A2" },
    { id: 3355, word: "Subject", meaning: "Konu", level: "A2" },
    { id: 3356, word: "Submit", meaning: "Sunmak, Teslim etmek", level: "B2" },
    { id: 3357, word: "Substance", meaning: "Madde", level: "B2" },
    { id: 3358, word: "Substantial", meaning: "Önemli, Varlıklı", level: "C1" },
    { id: 3359, word: "Substitute", meaning: "Yedek, Yerine geçen", level: "C1" },
    { id: 3360, word: "Succeed", meaning: "Başarmak", level: "A2" },
    { id: 3361, word: "Success", meaning: "Başarı", level: "A2" },
    { id: 3362, word: "Successful", meaning: "Başarılı", level: "A2" },
    { id: 3363, word: "Successfully", meaning: "Başarıyla", level: "B1" },
    { id: 3364, word: "Such", meaning: "Böyle", level: "A2" },
    { id: 3365, word: "Sudden", meaning: "Ani", level: "B1" },
    { id: 3366, word: "Suddenly", meaning: "Aniden", level: "A2" },
    { id: 3367, word: "Suffer", meaning: "Acı çekmek", level: "B1" },
    { id: 3368, word: "Sugar", meaning: "Şeker", level: "A2" },
    { id: 3369, word: "Suggest", meaning: "Önermek", level: "A2" },
    { id: 3370, word: "Suggestion", meaning: "Öneri", level: "A2" },
    { id: 3371, word: "Suit", meaning: "Takım elbise, Uymak", level: "A2" },
    { id: 3372, word: "Suitable", meaning: "Uygun", level: "B1" },
    { id: 3373, word: "Suitcase", meaning: "Valiz", level: "A2" },
    { id: 3374, word: "Sum", meaning: "Toplam", level: "B2" },
    { id: 3375, word: "Summary", meaning: "Özet", level: "B1" },
    { id: 3376, word: "Summer", meaning: "Yaz", level: "A2" },
    { id: 3377, word: "Sun", meaning: "Güneş", level: "A2" },
    { id: 3378, word: "Sunday", meaning: "Pazar", level: "A2" },
    { id: 3379, word: "Supermarket", meaning: "Süpermarket", level: "A2" },
    { id: 3380, word: "Support", meaning: "Desteklemek", level: "A2" },
    { id: 3381, word: "Supporter", meaning: "Destekçi", level: "B1" },
    { id: 3382, word: "Suppose", meaning: "Varsaymak", level: "A2" },
    { id: 3383, word: "Sure", meaning: "Emin", level: "A2" },
    { id: 3384, word: "Surely", meaning: "Kesinlikle", level: "B1" },
    { id: 3385, word: "Surface", meaning: "Yüzey", level: "B1" },
    { id: 3386, word: "Surgery", meaning: "Ameliyat", level: "B2" },
    { id: 3387, word: "Surprise", meaning: "Sürpriz", level: "A2" },
    { id: 3388, word: "Surprised", meaning: "Şaşırmış", level: "A2" },
    { id: 3389, word: "Surprising", meaning: "Şaşırtıcı", level: "A2" },
    { id: 3390, word: "Surround", meaning: "Çevrelemek", level: "B2" },
    { id: 3391, word: "Surrounding", meaning: "Çevreleyen", level: "B2" },
    { id: 3392, word: "Survey", meaning: "Anket", level: "B1" },
    { id: 3393, word: "Survival", meaning: "Hayatta kalma", level: "B1" },
    { id: 3394, word: "Survive", meaning: "Hayatta kalmak", level: "B1" },
    { id: 3395, word: "Suspect", meaning: "Şüphelenmek, Şüpheli", level: "B1" },
    { id: 3396, word: "Sustain", meaning: "Sürdürmek", level: "C1" },
    { id: 3397, word: "Sustainable", meaning: "Sürdürülebilir", level: "C1" },
    { id: 3398, word: "Swallow", meaning: "Yutmak, Kırlangıç", level: "B2" },
    { id: 3399, word: "Swear", meaning: "Yemin etmek, Küfretmek", level: "B2" },
    { id: 3400, word: "Sweat", meaning: "Ter", level: "B1" }
];
