[
    { id: 2501, word: "Oak", meaning: "Meşe", level: "B2" },
    { id: 2502, word: "Obey", meaning: "İtaat etmek", level: "B1" },
    { id: 2503, word: "Object", meaning: "Nesne, İtiraz etmek", level: "A2" },
    { id: 2504, word: "Objective", meaning: "Hedef, Nesnel", level: "B1" },
    { id: 2505, word: "Obligation", meaning: "Yükümlülük", level: "B2" },
    { id: 2506, word: "Observation", meaning: "Gözlem", level: "B1" },
    { id: 2507, word: "Observe", meaning: "Gözlemlemek", level: "B1" },
    { id: 2508, word: "Obvious", meaning: "Açık, Bariz", level: "B1" },
    { id: 2509, word: "Obviously", meaning: "Açıkça", level: "B1" },
    { id: 2510, word: "Occasion", meaning: "Fırsat, Durum", level: "B1" },
    { id: 2511, word: "Occasionally", meaning: "Ara sıra", level: "B1" },
    { id: 2512, word: "Occur", meaning: "Meydana gelmek", level: "B1" },
    { id: 2513, word: "Ocean", meaning: "Okyanus", level: "A2" },
    { id: 2514, word: "October", meaning: "Ekim", level: "A2" },
    { id: 2515, word: "Odd", meaning: "Garip, Tek (sayı)", level: "B1" },
    { id: 2516, word: "Of", meaning: "Onun, -ın, -in", level: "A2" },
    { id: 2517, word: "Off", meaning: "Kapalı, Uzak", level: "A2" },
    { id: 2518, word: "Offence", meaning: "Suç, Taarruz", level: "B1" },
    { id: 2519, word: "Offend", meaning: "Gücendirmek", level: "B2" },
    { id: 2520, word: "Offensive", meaning: "Saldırgan", level: "B1" },
    { id: 2521, word: "Offer", meaning: "Teklif etmek", level: "A2" },
    { id: 2522, word: "Office", meaning: "Ofis", level: "A2" },
    { id: 2523, word: "Officer", meaning: "Memur, Subay", level: "B1" },
    { id: 2524, word: "Official", meaning: "Resmi", level: "B1" },
    { id: 2525, word: "Often", meaning: "Sık sık", level: "A2" },
    { id: 2526, word: "Oh", meaning: "Ah, Ey", level: "A2" },
    { id: 2527, word: "Oil", meaning: "Yağ, Petrol", level: "A2" },
    { id: 2528, word: "Okay", meaning: "Tamam", level: "A2" },
    { id: 2529, word: "Old", meaning: "Eski, Yaşlı", level: "A2" },
    { id: 2530, word: "Old-fashioned", meaning: "Eski moda", level: "B1" },
    { id: 2531, word: "On", meaning: "Üzerinde", level: "A2" },
    { id: 2532, word: "Once", meaning: "Bir kez", level: "A2" },
    { id: 2533, word: "One", meaning: "Bir", level: "A2" },
    { id: 2534, word: "Onion", meaning: "Soğan", level: "A2" },
    { id: 2535, word: "Online", meaning: "Çevrimiçi", level: "A2" },
    { id: 2536, word: "Only", meaning: "Sadece", level: "A2" },
    { id: 2537, word: "Onto", meaning: "Üzerine", level: "A2" },
    { id: 2538, word: "Open", meaning: "Açık, Açmak", level: "A2" },
    { id: 2539, word: "Opening", meaning: "Açılış", level: "B1" },
    { id: 2540, word: "Operate", meaning: "İşletmek, Ameliyat etmek", level: "B2" },
    { id: 2541, word: "Operation", meaning: "Operasyon", level: "B1" },
    { id: 2542, word: "Opinion", meaning: "Görüş", level: "A2" },
    { id: 2543, word: "Opponent", meaning: "Rakip", level: "B2" },
    { id: 2544, word: "Opportunity", meaning: "Fırsat", level: "B1" },
    { id: 2545, word: "Opposite", meaning: "Zıt, Karşıt", level: "A2" },
    { id: 2546, word: "Opposition", meaning: "Muhalefet", level: "B2" },
    { id: 2547, word: "Option", meaning: "Seçenek", level: "B1" },
    { id: 2548, word: "Or", meaning: "Veya", level: "A2" },
    { id: 2549, word: "Orange", meaning: "Turuncu, Portakal", level: "A2" },
    { id: 2550, word: "Order", meaning: "Düzen, Emir, Sipariş", level: "A2" },
    { id: 2551, word: "Ordinary", meaning: "Sıradan", level: "B1" },
    { id: 2552, word: "Organization", meaning: "Organizasyon", level: "B1" },
    { id: 2553, word: "Organize", meaning: "Organize etmek", level: "B1" },
    { id: 2554, word: "Orient", meaning: "Yöneltmek, Doğu", level: "B2" },
    { id: 2555, word: "Original", meaning: "Orijinal", level: "B1" },
    { id: 2556, word: "Originally", meaning: "Aslen", level: "B1" },
    { id: 2557, word: "Other", meaning: "Diğer", level: "A2" },
    { id: 2558, word: "Otherwise", meaning: "Aksi takdirde", level: "B1" },
    { id: 2559, word: "Ought", meaning: "-meli, -malı", level: "B1" },
    { id: 2560, word: "Our", meaning: "Bizim", level: "A2" },
    { id: 2561, word: "Ours", meaning: "Bizimki", level: "B1" },
    { id: 2562, word: "Ourselves", meaning: "Kendimiz", level: "B1" },
    { id: 2563, word: "Out", meaning: "Dışarı", level: "A2" },
    { id: 2564, word: "Outcome", meaning: "Sonuç", level: "B2" },
    { id: 2565, word: "Outdoor", meaning: "Açık hava", level: "B1" },
    { id: 2566, word: "Outdoors", meaning: "Dışarıda", level: "B1" },
    { id: 2567, word: "Outer", meaning: "Dış", level: "B1" },
    { id: 2568, word: "Output", meaning: "Çıktı", level: "B2" },
    { id: 2569, word: "Outside", meaning: "Dışarıda", level: "A2" },
    { id: 2570, word: "Outstanding", meaning: "Olağanüstü", level: "B2" },
    { id: 2571, word: "Oven", meaning: "Fırın", level: "A2" },
    { id: 2572, word: "Over", meaning: "Üzerinde, Bitti", level: "A2" },
    { id: 2573, word: "Overall", meaning: "Genel, Toplam", level: "B2" },
    { id: 2574, word: "Overcome", meaning: "Üstesinden gelmek", level: "B2" },
    { id: 2575, word: "Overseas", meaning: "Deniz aşırı", level: "B2" },
    { id: 2576, word: "Owe", meaning: "Borçlu olmak", level: "B1" },
    { id: 2577, word: "Own", meaning: "Kendi", level: "A2" },
    { id: 2578, word: "Owner", meaning: "Sahip", level: "A2" },
    { id: 2579, word: "Pace", meaning: "Adım, Hız", level: "B1" },
    { id: 2580, word: "Pack", meaning: "Paketlemek", level: "A2" },
    { id: 2581, word: "Package", meaning: "Paket", level: "A2" },
    { id: 2582, word: "Packet", meaning: "Paket, Deste", level: "A2" },
    { id: 2583, word: "Pad", meaning: "Ped, Bloknot", level: "B2" },
    { id: 2584, word: "Page", meaning: "Sayfa", level: "A2" },
    { id: 2585, word: "Pain", meaning: "Ağrı", level: "A2" },
    { id: 2586, word: "Painful", meaning: "Ağrılı", level: "B1" },
    { id: 2587, word: "Paint", meaning: "Boyamak", level: "A2" },
    { id: 2588, word: "Painter", meaning: "Ressam", level: "B1" },
    { id: 2589, word: "Painting", meaning: "Tablo, Boyama", level: "A2" },
    { id: 2590, word: "Pair", meaning: "Çift", level: "A2" },
    { id: 2591, word: "Palace", meaning: "Saray", level: "A2" },
    { id: 2592, word: "Pale", meaning: "Soluk", level: "B1" },
    { id: 2593, word: "Pan", meaning: "Tava", level: "A2" },
    { id: 2594, word: "Panel", meaning: "Panel", level: "B2" },
    { id: 2595, word: "Pants", meaning: "Pantolon", level: "A2" },
    { id: 2596, word: "Paper", meaning: "Kağıt", level: "A2" },
    { id: 2597, word: "Paragraph", meaning: "Paragraf", level: "A2" },
    { id: 2598, word: "Parallel", meaning: "Paralel", level: "B2" },
    { id: 2599, word: "Parent", meaning: "Ebeveyn", level: "A2" },
    { id: 2600, word: "Park", meaning: "Park", level: "A2" },
    { id: 2601, word: "Parking", meaning: "Park etme", level: "A2" },
    { id: 2602, word: "Parliament", meaning: "Parlamento", level: "B2" },
    { id: 2603, word: "Part", meaning: "Parça, Bölüm", level: "A2" },
    { id: 2604, word: "Participate", meaning: "Katılmak", level: "B1" },
    { id: 2605, word: "Particular", meaning: "Belirli, Özel", level: "B1" },
    { id: 2606, word: "Particularly", meaning: "Özellikle", level: "B1" },
    { id: 2607, word: "Partly", meaning: "Kısmen", level: "B1" },
    { id: 2608, word: "Partner", meaning: "Partner", level: "A2" },
    { id: 2609, word: "Partnership", meaning: "Ortaklık", level: "B2" },
    { id: 2610, word: "Party", meaning: "Parti", level: "A2" },
    { id: 2611, word: "Pass", meaning: "Geçmek", level: "A2" },
    { id: 2612, word: "Passage", meaning: "Pasaj, Geçit", level: "B1" },
    { id: 2613, word: "Passenger", meaning: "Yolcu", level: "A2" },
    { id: 2614, word: "Passion", meaning: "Tutku", level: "B2" },
    { id: 2615, word: "Passive", meaning: "Edilgen", level: "B2" },
    { id: 2616, word: "Passport", meaning: "Pasaport", level: "A2" },
    { id: 2617, word: "Past", meaning: "Geçmiş", level: "A2" },
    { id: 2618, word: "Path", meaning: "Yol, Patika", level: "B1" },
    { id: 2619, word: "Patience", meaning: "Sabır", level: "B2" },
    { id: 2620, word: "Patient", meaning: "Hasta, Sabırlı", level: "A2" },
    { id: 2621, word: "Pattern", meaning: "Desen, Kalıp", level: "B1" },
    { id: 2622, word: "Pause", meaning: "Duraklamak", level: "B1" },
    { id: 2623, word: "Pay", meaning: "Ödemek", level: "A2" },
    { id: 2624, word: "Payment", meaning: "Ödeme", level: "B1" },
    { id: 2625, word: "Peace", meaning: "Barış", level: "A2" },
    { id: 2626, word: "Peaceful", meaning: "Huzurlu", level: "B1" },
    { id: 2627, word: "Peak", meaning: "Zirve", level: "B2" },
    { id: 2628, word: "Pen", meaning: "Kalem", level: "A2" },
    { id: 2629, word: "Penalty", meaning: "Ceza", level: "B2" },
    { id: 2630, word: "Pencil", meaning: "Kurşun kalem", level: "A2" },
    { id: 2631, word: "Penny", meaning: "Kuruş", level: "A2" },
    { id: 2632, word: "Pension", meaning: "Emekli maaşı", level: "B2" },
    { id: 2633, word: "People", meaning: "İnsanlar", level: "A2" },
    { id: 2634, word: "Pepper", meaning: "Biber", level: "A2" },
    { id: 2635, word: "Per", meaning: "Başına", level: "A2" },
    { id: 2636, word: "Percentage", meaning: "Yüzde", level: "B1" },
    { id: 2637, word: "Perfect", meaning: "Mükemmel", level: "A2" },
    { id: 2638, word: "Perfectly", meaning: "Mükemmelce", level: "B1" },
    { id: 2639, word: "Perform", meaning: "Sahnelemek, Yapmak", level: "B1" },
    { id: 2640, word: "Performance", meaning: "Performans", level: "B1" },
    { id: 2641, word: "Perhaps", meaning: "Belki", level: "A2" },
    { id: 2642, word: "Period", meaning: "Dönem", level: "A2" },
    { id: 2643, word: "Permanent", meaning: "Kalıcı", level: "B2" },
    { id: 2644, word: "Permission", meaning: "İzin", level: "B1" },
    { id: 2645, word: "Permit", meaning: "İzin vermek", level: "B2" },
    { id: 2646, word: "Person", meaning: "Kişi", level: "A2" },
    { id: 2647, word: "Personal", meaning: "Kişisel", level: "A2" },
    { id: 2648, word: "Personally", meaning: "Şahsen", level: "B1" },
    { id: 2649, word: "Perspective", meaning: "Perspektif", level: "B2" },
    { id: 2650, word: "Persuade", meaning: "İkna etmek", level: "B1" },
    { id: 2651, word: "Pet", meaning: "Evcil hayvan", level: "A2" },
    { id: 2652, word: "Petrol", meaning: "Benzin", level: "A2" },
    { id: 2653, word: "Phase", meaning: "Evre, Faz", level: "B2" },
    { id: 2654, word: "Phenomenon", meaning: "Fenomen, Olay", level: "C1" },
    { id: 2655, word: "Philosophy", meaning: "Felsefe", level: "C1" },
    { id: 2656, word: "Phone", meaning: "Telefon", level: "A2" },
    { id: 2657, word: "Photo", meaning: "Fotoğraf", level: "A2" },
    { id: 2658, word: "Photograph", meaning: "Fotoğraf", level: "A2" },
    { id: 2659, word: "Photographer", meaning: "Fotoğrafçı", level: "B1" },
    { id: 2660, word: "Photography", meaning: "Fotoğrafçılık", level: "B1" },
    { id: 2661, word: "Phrase", meaning: "İfade, Tabir", level: "A2" },
    { id: 2662, word: "Physical", meaning: "Fiziksel", level: "B1" },
    { id: 2663, word: "Physics", meaning: "Fizik", level: "A2" },
    { id: 2664, word: "Pianist", meaning: "Piyanist", level: "A2" },
    { id: 2665, word: "Piano", meaning: "Piyano", level: "A2" },
    { id: 2666, word: "Pick", meaning: "Seçmek", level: "A2" },
    { id: 2667, word: "Picture", meaning: "Resim", level: "A2" },
    { id: 2668, word: "Piece", meaning: "Parça", level: "A2" },
    { id: 2669, word: "Pig", meaning: "Domuz", level: "A2" },
    { id: 2670, word: "Pile", meaning: "Yığın", level: "B1" },
    { id: 2671, word: "Pill", meaning: "Hap", level: "B1" },
    { id: 2672, word: "Pilot", meaning: "Pilot", level: "A2" },
    { id: 2673, word: "Pin", meaning: "İğne, Rapdiye", level: "B2" },
    { id: 2674, word: "Pink", meaning: "Pembe", level: "A2" },
    { id: 2675, word: "Pipe", meaning: "Boru, Pipo", level: "B1" },
    { id: 2676, word: "Pirate", meaning: "Korsan", level: "B1" },
    { id: 2677, word: "Pit", meaning: "Çukur", level: "B2" },
    { id: 2678, word: "Pitch", meaning: "Saha, Zift", level: "B2" },
    { id: 2679, word: "Pity", meaning: "Yazık, Acıma", level: "B1" },
    { id: 2680, word: "Place", meaning: "Yer", level: "A2" },
    { id: 2681, word: "Plain", meaning: "Sade, Ova", level: "B1" },
    { id: 2682, word: "Plan", meaning: "Plan", level: "A2" },
    { id: 2683, word: "Plane", meaning: "Uçak", level: "A2" },
    { id: 2684, word: "Planet", meaning: "Gezegen", level: "A2" },
    { id: 2685, word: "Planning", meaning: "Planlama", level: "B1" },
    { id: 2686, word: "Plant", meaning: "Bitki, Tesis", level: "A2" },
    { id: 2687, word: "Plastic", meaning: "Plastik", level: "A2" },
    { id: 2688, word: "Plate", meaning: "Plaka, Tabak", level: "A2" },
    { id: 2689, word: "Platform", meaning: "Platform", level: "B1" },
    { id: 2690, word: "Play", meaning: "Oynamak", level: "A2" },
    { id: 2691, word: "Player", meaning: "Oyuncu", level: "A2" },
    { id: 2692, word: "Pleasant", meaning: "Keyifli", level: "B1" },
    { id: 2693, word: "Please", meaning: "Lütfen", level: "A2" },
    { id: 2694, word: "Pleased", meaning: "Memnun", level: "A2" },
    { id: 2695, word: "Pleasure", meaning: "Zevk", level: "B1" },
    { id: 2696, word: "Plenty", meaning: "Bolca", level: "A2" },
    { id: 2697, word: "Plot", meaning: "Konu, Arsa", level: "B1" },
    { id: 2698, word: "Plug", meaning: "Fiş", level: "B1" },
    { id: 2699, word: "Pocket", meaning: "Cep", level: "A2" },
    { id: 2700, word: "Poem", meaning: "Şiir", level: "B1" },
    { id: 2701, word: "Poet", meaning: "Şair", level: "B1" },
    { id: 2702, word: "Poetry", meaning: "Şiir (Sanat)", level: "B2" },
    { id: 2703, word: "Point", meaning: "Nokta, Puan", level: "A2" },
    { id: 2704, word: "Pointless", meaning: "Anlamsız", level: "B2" },
    { id: 2705, word: "Poison", meaning: "Zehir", level: "B1" },
    { id: 2706, word: "Poisonous", meaning: "Zehirli", level: "B2" },
    { id: 2707, word: "Pole", meaning: "Direk, Kutup", level: "B2" },
    { id: 2708, word: "Police", meaning: "Polis", level: "A2" },
    { id: 2709, word: "Policeman", meaning: "Polis memuru", level: "A2" },
    { id: 2710, word: "Policy", meaning: "Politika, İlke", level: "B1" },
    { id: 2711, word: "Polish", meaning: "Cilalamak", level: "B2" },
    { id: 2712, word: "Polite", meaning: "Nazik", level: "B1" },
    { id: 2713, word: "Political", meaning: "Siyasi", level: "B1" },
    { id: 2714, word: "Politician", meaning: "Politikacı", level: "B1" },
    { id: 2715, word: "Politics", meaning: "Politika", level: "B1" },
    { id: 2716, word: "Poll", meaning: "Anket", level: "B2" },
    { id: 2717, word: "Pollution", meaning: "Kirlilik", level: "B1" },
    { id: 2718, word: "Pool", meaning: "Havuz", level: "A2" },
    { id: 2719, word: "Poor", meaning: "Fakir", level: "A2" },
    { id: 2720, word: "Pop", meaning: "Pop (Müzik)", level: "A2" },
    { id: 2721, word: "Popular", meaning: "Popüler", level: "A2" },
    { id: 2722, word: "Population", meaning: "Nüfus", level: "B1" },
    { id: 2723, word: "Port", meaning: "Liman", level: "B1" },
    { id: 2724, word: "Portfolio", meaning: "Portfolyo", level: "B2" },
    { id: 2725, word: "Portion", meaning: "Porsiyon", level: "B1" },
    { id: 2726, word: "Portrait", meaning: "Portre", level: "A2" },
    { id: 2727, word: "Position", meaning: "Pozisyon", level: "A2" },
    { id: 2728, word: "Positive", meaning: "Pozitif", level: "A2" },
    { id: 2729, word: "Possess", meaning: "Sahip olmak", level: "B2" },
    { id: 2730, word: "Possession", meaning: "Mülk, Sahiplik", level: "B2" },
    { id: 2731, word: "Possibility", meaning: "Olasılık", level: "B1" },
    { id: 2732, word: "Possible", meaning: "Mümkün", level: "A2" },
    { id: 2733, word: "Possibly", meaning: "Muhtemelen", level: "A2" },
    { id: 2734, word: "Post", meaning: "Posta, Gönderi", level: "A2" },
    { id: 2735, word: "Postbox", meaning: "Posta kutusu", level: "B1" },
    { id: 2736, word: "Poster", meaning: "Poster", level: "A2" },
    { id: 2737, word: "Pot", meaning: "Tencere", level: "A2" },
    { id: 2738, word: "Potato", meaning: "Patates", level: "A2" },
    { id: 2739, word: "Potential", meaning: "Potansiyel", level: "B1" },
    { id: 2740, word: "Potentially", meaning: "Potansiyel olarak", level: "B2" },
    { id: 2741, word: "Pound", meaning: "Pound (Para/Ağırlık)", level: "A2" },
    { id: 2742, word: "Pour", meaning: "Dökmek", level: "B1" },
    { id: 2743, word: "Poverty", meaning: "Yoksulluk", level: "B2" },
    { id: 2744, word: "Powder", meaning: "Toz", level: "B1" },
    { id: 2745, word: "Power", meaning: "Güç", level: "A2" },
    { id: 2746, word: "Powerful", meaning: "Güçlü", level: "B1" },
    { id: 2747, word: "Practical", meaning: "Pratik", level: "B1" },
    { id: 2748, word: "Practice", meaning: "Pratik, Uygulama", level: "A2" },
    { id: 2749, word: "Practise", meaning: "Alıştırma yapmak", level: "A2" },
    { id: 2750, word: "Praise", meaning: "Övmek", level: "B2" },
    { id: 2751, word: "Prayer", meaning: "Dua", level: "B2" },
    { id: 2752, word: "Precise", meaning: "Hassas, Kesin", level: "B1" },
    { id: 2753, word: "Predict", meaning: "Tahmin etmek", level: "B1" },
    { id: 2754, word: "Prefer", meaning: "Tercih etmek", level: "A2" },
    { id: 2755, word: "Preference", meaning: "Tercih", level: "B2" },
    { id: 2756, word: "Pregnant", meaning: "Hamile", level: "B1" },
    { id: 2757, word: "Preparation", meaning: "Hazırlık", level: "B1" },
    { id: 2758, word: "Prepare", meaning: "Hazırlamak", level: "A2" },
    { id: 2759, word: "Presence", meaning: "Varlık", level: "B2" },
    { id: 2760, word: "Present", meaning: "Mevcut, Hediye, Sunmak", level: "A2" },
    { id: 2761, word: "Presentation", meaning: "Sunum", level: "B1" },
    { id: 2762, word: "Preserve", meaning: "Korumak, Muhafaza etmek", level: "B2" },
    { id: 2763, word: "President", meaning: "Başkan", level: "A2" },
    { id: 2764, word: "Press", meaning: "Basın, Basmak", level: "B1" },
    { id: 2765, word: "Pressure", meaning: "Basınç", level: "B1" },
    { id: 2766, word: "Presumably", meaning: "Muhtemelen", level: "B2" },
    { id: 2767, word: "Pretend", meaning: "Yapar gibi görünmek", level: "B1" },
    { id: 2768, word: "Pretty", meaning: "Güzel, Epey", level: "A2" },
    { id: 2769, word: "Prevent", meaning: "Önlemek", level: "B1" },
    { id: 2770, word: "Previous", meaning: "Önceki", level: "B1" },
    { id: 2771, word: "Previously", meaning: "Önceden", level: "B1" },
    { id: 2772, word: "Price", meaning: "Fiyat", level: "A2" },
    { id: 2773, word: "Pride", meaning: "Gurur", level: "B1" },
    { id: 2774, word: "Priest", meaning: "Rahip", level: "B2" },
    { id: 2775, word: "Primary", meaning: "Birincil, İlkokul", level: "B2" },
    { id: 2776, word: "Prime", meaning: "Başlıca", level: "B2" },
    { id: 2777, word: "Prince", meaning: "Prens", level: "A2" },
    { id: 2778, word: "Princess", meaning: "Prenses", level: "A2" },
    { id: 2779, word: "Principal", meaning: "Okul müdürü, Başlıca", level: "B2" },
    { id: 2780, word: "Principle", meaning: "Prensip", level: "B2" },
    { id: 2781, word: "Print", meaning: "Basmak, Yazdırmak", level: "A2" },
    { id: 2782, word: "Printer", meaning: "Yazıcı", level: "A2" },
    { id: 2783, word: "Prior", meaning: "Önceki", level: "B1" },
    { id: 2784, word: "Priority", meaning: "Öncelik", level: "B2" },
    { id: 2785, word: "Prison", meaning: "Hapishane", level: "A2" },
    { id: 2786, word: "Prisoner", meaning: "Mahkum", level: "B1" },
    { id: 2787, word: "Private", meaning: "Özel", level: "B1" },
    { id: 2788, word: "Prize", meaning: "Ödül", level: "A2" },
    { id: 2789, word: "Probably", meaning: "Muhtemelen", level: "A2" },
    { id: 2790, word: "Problem", meaning: "Sorun", level: "A2" },
    { id: 2791, word: "Procedure", meaning: "Prosedür", level: "B2" },
    { id: 2792, word: "Process", meaning: "Süreç", level: "B1" },
    { id: 2793, word: "Produce", meaning: "Üretmek", level: "A2" },
    { id: 2794, word: "Producer", meaning: "Yapımcı", level: "B1" },
    { id: 2795, word: "Product", meaning: "Ürün", level: "A2" },
    { id: 2796, word: "Production", meaning: "Üretim", level: "B1" },
    { id: 2797, word: "Profession", meaning: "Meslek", level: "B1" },
    { id: 2798, word: "Professional", meaning: "Profesyonel", level: "B1" },
    { id: 2799, word: "Professor", meaning: "Profesör", level: "B1" },
    { id: 2800, word: "Profile", meaning: "Profil", level: "A2" }
];
