window.WORD_DATA_PART1 = [
    // A2 Essentials
    { id: 1001, word: "Ability", meaning: "Yetenek", level: "A2" },
    { id: 1002, word: "Abroad", meaning: "Yurt dışı", level: "A2" },
    { id: 1003, word: "Accept", meaning: "Kabul etmek", level: "A2" },
    { id: 1004, word: "Access", meaning: "Erişim", level: "B1" },
    { id: 1005, word: "Accident", meaning: "Kaza", level: "A2" },
    { id: 1006, word: "Account", meaning: "Hesap", level: "B1" },
    { id: 1007, word: "Achieve", meaning: "Başarmak", level: "B1" },
    { id: 1008, word: "Act", meaning: "Hareket etmek", level: "A2" },
    { id: 1009, word: "Action", meaning: "Eylem", level: "A2" },
    { id: 1010, word: "Active", meaning: "Aktif", level: "A2" },
    { id: 1011, word: "Activity", meaning: "Aktivite", level: "A2" },
    { id: 1012, word: "Actually", meaning: "Aslında", level: "A2" },
    { id: 1013, word: "Adult", meaning: "Yetişkin", level: "A2" },
    { id: 1014, word: "Advantage", meaning: "Avantaj", level: "A2" },
    { id: 1015, word: "Adventure", meaning: "Macera", level: "A2" },
    { id: 1016, word: "Advertise", meaning: "Reklam yapmak", level: "A2" },
    { id: 1017, word: "Advice", meaning: "Tavsiye", level: "A2" },
    { id: 1018, word: "Affect", meaning: "Etkilemek", level: "A2" },
    { id: 1019, word: "Afraid", meaning: "Korkmuş", level: "A2" },
    { id: 1020, word: "After", meaning: "Sonra", level: "A2" },
    { id: 1021, word: "Against", meaning: "Karşı", level: "A2" },
    { id: 1022, word: "Agency", meaning: "Ajans", level: "B1" },
    { id: 1023, word: "Agree", meaning: "Katılmak", level: "A2" },
    { id: 1024, word: "Agreement", meaning: "Anlaşma", level: "B1" },
    { id: 1025, word: "Ahead", meaning: "İlerde", level: "B1" },
    { id: 1026, word: "Aim", meaning: "Amaç", level: "B1" },
    { id: 1027, word: "Airline", meaning: "Havayolu", level: "A2" },
    { id: 1028, word: "Airport", meaning: "Havalimanı", level: "A2" },
    { id: 1029, word: "Alarm", meaning: "Alarm", level: "B1" },
    { id: 1030, word: "Alive", meaning: "Canlı", level: "A2" },
    { id: 1031, word: "All", meaning: "Hepsi", level: "A2" },
    { id: 1032, word: "Allow", meaning: "İzin vermek", level: "A2" },
    { id: 1033, word: "Almost", meaning: "Neredeyse", level: "A2" },
    { id: 1034, word: "Alone", meaning: "Yalnız", level: "A2" },
    { id: 1035, word: "Along", meaning: "Boyunca", level: "A2" },
    { id: 1036, word: "Already", meaning: "Zaten", level: "A2" },
    { id: 1037, word: "Also", meaning: "Ayrıca", level: "A2" },
    { id: 1038, word: "Alternative", meaning: "Alternatif", level: "B1" },
    { id: 1039, word: "Although", meaning: "Rağmen", level: "B1" },
    { id: 1040, word: "Always", meaning: "Her zaman", level: "A2" },
    { id: 1041, word: "Amazing", meaning: "Şaşırtıcı", level: "A2" },
    { id: 1042, word: "Ambition", meaning: "Hırs", level: "B1" },
    { id: 1043, word: "Among", meaning: "Arasında", level: "A2" },
    { id: 1044, word: "Amount", meaning: "Miktar", level: "A2" },
    { id: 1045, word: "Analyse", meaning: "Analiz etmek", level: "B1" },
    { id: 1046, word: "Analysis", meaning: "Analiz", level: "B1" },
    { id: 1047, word: "Ancient", meaning: "Antik", level: "A2" },
    { id: 1048, word: "Angry", meaning: "Kızgın", level: "A2" },
    { id: 1049, word: "Animal", meaning: "Hayvan", level: "A2" },
    { id: 1050, word: "Ankle", meaning: "Ayak bileği", level: "A2" },
    { id: 1051, word: "Anniversary", meaning: "Yıl dönümü", level: "B1" },
    { id: 1052, word: "Announce", meaning: "Duyurmak", level: "B1" },
    { id: 1053, word: "Annoy", meaning: "Rahatsız etmek", level: "B1" },
    { id: 1054, word: "Annual", meaning: "Yıllık", level: "B1" },
    { id: 1055, word: "Another", meaning: "Diğer", level: "A2" },
    { id: 1056, word: "Answer", meaning: "Cevap", level: "A2" },
    { id: 1057, word: "Anxious", meaning: "Endişeli", level: "B1" },
    { id: 1058, word: "Any", meaning: "Herhangi", level: "A2" },
    { id: 1059, word: "Anybody", meaning: "Herhangi biri", level: "A2" },
    { id: 1060, word: "Anywhere", meaning: "Herhangi bir yer", level: "A2" },
    { id: 1061, word: "Apart", meaning: "Ayrı", level: "B1" },
    { id: 1062, word: "Apartment", meaning: "Daire", level: "A2" },
    { id: 1063, word: "Apologize", meaning: "Özür dilemek", level: "B1" },
    { id: 1064, word: "App", meaning: "Uygulama", level: "A2" },
    { id: 1065, word: "Appear", meaning: "Görünmek", level: "A2" },
    { id: 1066, word: "Appearance", meaning: "Görünüş", level: "A2" },
    { id: 1067, word: "Application", meaning: "Başvuru", level: "B1" },
    { id: 1068, word: "Apply", meaning: "Uygulamak", level: "A2" },
    { id: 1069, word: "Appointment", meaning: "Randevu", level: "B1" },
    { id: 1070, word: "Appreciate", meaning: "Takdir etmek", level: "B1" },
    { id: 1071, word: "Approach", meaning: "Yaklaşım", level: "B1" },
    { id: 1072, word: "Approximate", meaning: "Yaklaşık", level: "B1" },
    { id: 1073, word: "Architect", meaning: "Mimar", level: "A2" },
    { id: 1074, word: "Architecture", meaning: "Mimari", level: "A2" },
    { id: 1075, word: "Area", meaning: "Alan", level: "A2" },
    { id: 1076, word: "Argue", meaning: "Tartışmak", level: "A2" },
    { id: 1077, word: "Argument", meaning: "Argüman", level: "A2" },
    { id: 1078, word: "Army", meaning: "Ordu", level: "A2" },
    { id: 1079, word: "Arrange", meaning: "Düzenlemek", level: "A2" },
    { id: 1080, word: "Arrangement", meaning: "Düzenleme", level: "B1" },
    { id: 1081, word: "Arrest", meaning: "Tutuklamak", level: "B1" },
    { id: 1082, word: "Arrival", meaning: "Varış", level: "B1" },
    { id: 1083, word: "Arrive", meaning: "Varmak", level: "A2" },
    { id: 1084, word: "Art", meaning: "Sanat", level: "A2" },
    { id: 1085, word: "Article", meaning: "Makale", level: "A2" },
    { id: 1086, word: "Artificial", meaning: "Yapay", level: "B1" },
    { id: 1087, word: "Artist", meaning: "Sanatçı", level: "A2" },
    { id: 1088, word: "Artistic", meaning: "Sanatsal", level: "B1" },
    { id: 1089, word: "As", meaning: "Olarak", level: "A2" },
    { id: 1090, word: "Ashamed", meaning: "Utanmış", level: "B1" },
    { id: 1091, word: "Asleep", meaning: "Uykuda", level: "A2" },
    { id: 1092, word: "Aspect", meaning: "Yön, Bakış açısı", level: "B2" },
    { id: 1093, word: "Assess", meaning: "Değerlendirmek", level: "B2" },
    { id: 1094, word: "Assessment", meaning: "Değerlendirme", level: "B2" },
    { id: 1095, word: "Assignment", meaning: "Ödev, Atama", level: "B1" },
    { id: 1096, word: "Assist", meaning: "Yardım etmek", level: "B1" },
    { id: 1097, word: "Assistant", meaning: "Asistan", level: "A2" },
    { id: 1098, word: "Associate", meaning: "İlişkilendirmek", level: "B2" },
    { id: 1099, word: "Assumption", meaning: "Varsayım", level: "B2" },
    { id: 1100, word: "Atmosphere", meaning: "Atmosfer", level: "B1" },
    { id: 1101, word: "Attach", meaning: "Eklemek", level: "B1" },
    { id: 1102, word: "Attack", meaning: "Saldırı", level: "A2" },
    { id: 1103, word: "Attempt", meaning: "Girişim", level: "B1" },
    { id: 1104, word: "Attend", meaning: "Katılmak", level: "A2" },
    { id: 1105, word: "Attention", meaning: "Dikkat", level: "A2" },
    { id: 1106, word: "Attitude", meaning: "Tutum", level: "B1" },
    { id: 1107, word: "Attract", meaning: "Çekmek (ilgi)", level: "B1" },
    { id: 1108, word: "Attraction", meaning: "Cazibe", level: "B1" },
    { id: 1109, word: "Attractive", meaning: "Çekici", level: "A2" },
    { id: 1110, word: "Audience", meaning: "Seyirci", level: "B1" },
    { id: 1111, word: "Author", meaning: "Yazar", level: "A2" },
    { id: 1112, word: "Authority", meaning: "Otorite", level: "B1" },
    { id: 1113, word: "Available", meaning: "Mevcut", level: "A2" },
    { id: 1114, word: "Average", meaning: "Ortalama", level: "A2" },
    { id: 1115, word: "Avoid", meaning: "Kaçınmak", level: "A2" },
    { id: 1116, word: "Award", meaning: "Ödül", level: "A2" },
    { id: 1117, word: "Aware", meaning: "Farkında", level: "B1" },
    { id: 1118, word: "Away", meaning: "Uzakta", level: "A2" },
    { id: 1119, word: "Awful", meaning: "Berbat", level: "A2" },
    { id: 1120, word: "Baby", meaning: "Bebek", level: "A2" },
    { id: 1121, word: "Back", meaning: "Sırt, Geri", level: "A2" },
    { id: 1122, word: "Background", meaning: "Arka plan", level: "A2" },
    { id: 1123, word: "Backward", meaning: "Geriye doğru", level: "B1" },
    { id: 1124, word: "Bacteria", meaning: "Bakteri", level: "B2" },
    { id: 1125, word: "Bad", meaning: "Kötü", level: "A2" },
    { id: 1126, word: "Badly", meaning: "Kötü bir şekilde", level: "A2" },
    { id: 1127, word: "Bag", meaning: "Çanta", level: "A2" },
    { id: 1128, word: "Bake", meaning: "Fırında pişirmek", level: "A2" },
    { id: 1129, word: "Balance", meaning: "Denge", level: "B1" },
    { id: 1130, word: "Ball", meaning: "Top", level: "A2" },
    { id: 1131, word: "Ban", meaning: "Yasaklamak", level: "B1" },
    { id: 1132, word: "Band", meaning: "Müzik grubu", level: "A2" },
    { id: 1133, word: "Bank", meaning: "Banka", level: "A2" },
    { id: 1134, word: "Bar", meaning: "Çubuk, Bar", level: "A2" },
    { id: 1135, word: "Barrier", meaning: "Bariyer", level: "B2" },
    { id: 1136, word: "Base", meaning: "Taban, Üs", level: "B1" },
    { id: 1137, word: "Basic", meaning: "Temel", level: "B1" },
    { id: 1138, word: "Basically", meaning: "Temelde", level: "B1" },
    { id: 1139, word: "Basis", meaning: "Temel", level: "B1" },
    { id: 1140, word: "Bath", meaning: "Banyo", level: "A2" },
    { id: 1141, word: "Bathroom", meaning: "Banyo odası", level: "A2" },
    { id: 1142, word: "Battery", meaning: "Pil", level: "B1" },
    { id: 1143, word: "Battle", meaning: "Savaş", level: "B1" },
    { id: 1144, word: "Beach", meaning: "Plaj", level: "A2" },
    { id: 1145, word: "Bean", meaning: "Fasulye", level: "A2" },
    { id: 1146, word: "Bear", meaning: "Ayı, Katlanmak", level: "B1" },
    { id: 1147, word: "Beat", meaning: "Vurmak, Yenmek", level: "A2" },
    { id: 1148, word: "Beautiful", meaning: "Güzel", level: "A2" },
    { id: 1149, word: "Beauty", meaning: "Güzellik", level: "B1" },
    { id: 1150, word: "Become", meaning: "Olmak (dönüşmek)", level: "A2" },
    { id: 1151, word: "Bed", meaning: "Yatak", level: "A2" },
    { id: 1152, word: "Bedroom", meaning: "Yatak odası", level: "A2" },
    { id: 1153, word: "Before", meaning: "Önce", level: "A2" },
    { id: 1154, word: "Begin", meaning: "Başlamak", level: "A2" },
    { id: 1155, word: "Beginning", meaning: "Başlangıç", level: "A2" },
    { id: 1156, word: "Behave", meaning: "Davranmak", level: "A2" },
    { id: 1157, word: "Behavior", meaning: "Davranış", level: "A2" },
    { id: 1158, word: "Behind", meaning: "Arkada", level: "A2" },
    { id: 1159, word: "Belief", meaning: "İnanç", level: "B1" },
    { id: 1160, word: "Believe", meaning: "İnanmak", level: "A2" },
    { id: 1161, word: "Bell", meaning: "Zil", level: "B1" },
    { id: 1162, word: "Belong", meaning: "Ait olmak", level: "A2" },
    { id: 1163, word: "Below", meaning: "Aşağıda", level: "A2" },
    { id: 1164, word: "Belt", meaning: "Kemer", level: "A2" },
    { id: 1165, word: "Bend", meaning: "Eğmek", level: "B1" },
    { id: 1166, word: "Benefit", meaning: "Fayda", level: "A2" },
    { id: 1167, word: "Best", meaning: "En iyi", level: "A2" },
    { id: 1168, word: "Bet", meaning: "Bahis", level: "B1" },
    { id: 1169, word: "Better", meaning: "Daha iyi", level: "A2" },
    { id: 1170, word: "Between", meaning: "Arasında", level: "A2" },
    { id: 1171, word: "Beyond", meaning: "Ötesinde", level: "B1" },
    { id: 1172, word: "Bicycle", meaning: "Bisiklet", level: "A2" },
    { id: 1173, word: "Big", meaning: "Büyük", level: "A2" },
    { id: 1174, word: "Bike", meaning: "Bisiklet", level: "A2" },
    { id: 1175, word: "Bill", meaning: "Fatura", level: "A2" },
    { id: 1176, word: "Billion", meaning: "Milyar", level: "A2" },
    { id: 1177, word: "Bin", meaning: "Çöp kutusu", level: "A2" },
    { id: 1178, word: "Biology", meaning: "Biyoloji", level: "A2" },
    { id: 1179, word: "Bird", meaning: "Kuş", level: "A2" },
    { id: 1180, word: "Birth", meaning: "Doğum", level: "A2" },
    { id: 1181, word: "Birthday", meaning: "Doğum günü", level: "A2" },
    { id: 1182, word: "Biscuit", meaning: "Bisküvi", level: "A2" },
    { id: 1183, word: "Bit", meaning: "Biraz", level: "A2" },
    { id: 1184, word: "Bite", meaning: "Isırmak", level: "B1" },
    { id: 1185, word: "Bitter", meaning: "Acı", level: "B1" },
    { id: 1186, word: "Black", meaning: "Siyah", level: "A2" },
    { id: 1187, word: "Blame", meaning: "Suçlamak", level: "B1" },
    { id: 1188, word: "Blank", meaning: "Boş", level: "A2" },
    { id: 1189, word: "Blind", meaning: "Kör", level: "B1" },
    { id: 1190, word: "Block", meaning: "Blok, Engellemek", level: "B1" },
    { id: 1191, word: "Blog", meaning: "Blog", level: "A2" },
    { id: 1192, word: "Blonde", meaning: "Sarışın", level: "A2" },
    { id: 1193, word: "Blood", meaning: "Kan", level: "A2" },
    { id: 1194, word: "Blow", meaning: "Üflemek", level: "B1" },
    { id: 1195, word: "Blue", meaning: "Mavi", level: "A2" },
    { id: 1196, word: "Board", meaning: "Tahta, Kurul", level: "A2" },
    { id: 1197, word: "Boat", meaning: "Tekne", level: "A2" },
    { id: 1198, word: "Body", meaning: "Vücut", level: "A2" },
    { id: 1199, word: "Boil", meaning: "Kaynamak", level: "A2" },
    { id: 1200, word: "Bomb", meaning: "Bomba", level: "B1" }
