[
    { id: 1201, word: "Bond", meaning: "Bağ", level: "B2" },
    { id: 1202, word: "Bone", meaning: "Kemik", level: "A2" },
    { id: 1203, word: "Book", meaning: "Kitap, Rezerv etmek", level: "A2" },
    { id: 1204, word: "Boot", meaning: "Bot", level: "A2" },
    { id: 1205, word: "Border", meaning: "Sınır", level: "B1" },
    { id: 1206, word: "Bored", meaning: "Sıkılmış", level: "A2" },
    { id: 1207, word: "Boring", meaning: "Sıkıcı", level: "A2" },
    { id: 1208, word: "Born", meaning: "Doğmuş", level: "A2" },
    { id: 1209, word: "Borrow", meaning: "Ödünç almak", level: "A2" },
    { id: 1210, word: "Boss", meaning: "Patron", level: "A2" },
    { id: 1211, word: "Both", meaning: "Her ikisi", level: "A2" },
    { id: 1212, word: "Bother", meaning: "Rahatsız etmek", level: "B1" },
    { id: 1213, word: "Bottle", meaning: "Şişe", level: "A2" },
    { id: 1214, word: "Bottom", meaning: "Dip", level: "A2" },
    { id: 1215, word: "Bowl", meaning: "Kase", level: "A2" },
    { id: 1216, word: "Box", meaning: "Kutu", level: "A2" },
    { id: 1217, word: "Boy", meaning: "Erkek çocuk", level: "A2" },
    { id: 1218, word: "Brain", meaning: "Beyin", level: "A2" },
    { id: 1219, word: "Branch", meaning: "Dal, Şube", level: "B1" },
    { id: 1220, word: "Brand", meaning: "Marka", level: "B1" },
    { id: 1221, word: "Brave", meaning: "Cesur", level: "B1" },
    { id: 1222, word: "Bread", meaning: "Ekmek", level: "A2" },
    { id: 1223, word: "Break", meaning: "Kırmak, Mola", level: "A2" },
    { id: 1224, word: "Breakfast", meaning: "Kahvaltı", level: "A2" },
    { id: 1225, word: "Breath", meaning: "Nefes", level: "B1" },
    { id: 1226, word: "Breathe", meaning: "Nefes almak", level: "B1" },
    { id: 1227, word: "Breathing", meaning: "Solunum", level: "B1" },
    { id: 1228, word: "Bride", meaning: "Gelin", level: "B1" },
    { id: 1229, word: "Bridge", meaning: "Köprü", level: "A2" },
    { id: 1230, word: "Brief", meaning: "Kısa, Öz", level: "B2" },
    { id: 1231, word: "Bright", meaning: "Parlak", level: "A2" },
    { id: 1232, word: "Brilliant", meaning: "Muhteşem", level: "A2" },
    { id: 1233, word: "Bring", meaning: "Getirmek", level: "A2" },
    { id: 1234, word: "Broad", meaning: "Geniş", level: "B2" },
    { id: 1235, word: "Broadcast", meaning: "Yayın, Yayınlamak", level: "B2" },
    { id: 1236, word: "Broken", meaning: "Kırık", level: "A2" },
    { id: 1237, word: "Brother", meaning: "Erkek kardeş", level: "A2" },
    { id: 1238, word: "Brown", meaning: "Kahverengi", level: "A2" },
    { id: 1239, word: "Brush", meaning: "Fırça, Fırçalamak", level: "A2" },
    { id: 1240, word: "Bubble", meaning: "Baloncuk", level: "B1" },
    { id: 1241, word: "Budget", meaning: "Bütçe", level: "B2" },
    { id: 1242, word: "Build", meaning: "İnşa etmek", level: "A2" },
    { id: 1243, word: "Building", meaning: "Bina", level: "A2" },
    { id: 1244, word: "Bullet", meaning: "Mermi", level: "B2" },
    { id: 1245, word: "Bunch", meaning: "Demet, Salkım", level: "B2" },
    { id: 1246, word: "Burn", meaning: "Yanmak, Yakmak", level: "A2" },
    { id: 1247, word: "Bury", meaning: "Gömmek", level: "B1" },
    { id: 1248, word: "Bus", meaning: "Otobüs", level: "A2" },
    { id: 1249, word: "Bush", meaning: "Çalı", level: "B2" },
    { id: 1250, word: "Business", meaning: "İş", level: "A2" },
    { id: 1251, word: "Businessman", meaning: "İş adamı", level: "A2" },
    { id: 1252, word: "Busy", meaning: "Meşgul", level: "A2" },
    { id: 1253, word: "But", meaning: "Ama", level: "A2" },
    { id: 1254, word: "Butter", meaning: "Tereyağı", level: "A2" },
    { id: 1255, word: "Button", meaning: "Düğme", level: "A2" },
    { id: 1256, word: "Buy", meaning: "Satın almak", level: "A2" },
    { id: 1257, word: "By", meaning: "Tarafından", level: "A2" },
    { id: 1258, word: "Bye", meaning: "Hoşçakal", level: "A2" },
    { id: 1259, word: "Cable", meaning: "Kablo", level: "B2" },
    { id: 1260, word: "Cafe", meaning: "Kafe", level: "A2" },
    { id: 1261, word: "Cake", meaning: "Kek", level: "A2" },
    { id: 1262, word: "Calculate", meaning: "Hesaplamak", level: "B2" },
    { id: 1263, word: "Call", meaning: "Aramak", level: "A2" },
    { id: 1264, word: "Calm", meaning: "Sakin", level: "B1" },
    { id: 1265, word: "Camera", meaning: "Kamera", level: "A2" },
    { id: 1266, word: "Camp", meaning: "Kamp", level: "A2" },
    { id: 1267, word: "Campaign", meaning: "Kampanya", level: "B1" },
    { id: 1268, word: "Camping", meaning: "Kamp yapma", level: "A2" },
    { id: 1269, word: "Campus", meaning: "Kampüs", level: "B1" },
    { id: 1270, word: "Can", meaning: "Yapabilmek", level: "A2" },
    { id: 1271, word: "Cancel", meaning: "İptal etmek", level: "B2" },
    { id: 1272, word: "Cancer", meaning: "Kanser", level: "B2" },
    { id: 1273, word: "Candidate", meaning: "Aday", level: "B1" },
    { id: 1274, word: "Candy", meaning: "Şeker", level: "A2" },
    { id: 1275, word: "Cap", meaning: "Kapak, Şapka", level: "B1" },
    { id: 1276, word: "Capable", meaning: "Kabiliyetli", level: "B2" },
    { id: 1277, word: "Capacity", meaning: "Kapasite", level: "B2" },
    { id: 1278, word: "Capital", meaning: "Başkent, Sermaye", level: "A2" },
    { id: 1279, word: "Captain", meaning: "Kaptan", level: "B1" },
    { id: 1280, word: "Capture", meaning: "Yakalamak", level: "B2" },
    { id: 1281, word: "Car", meaning: "Araba", level: "A2" },
    { id: 1282, word: "Card", meaning: "Kart", level: "A2" },
    { id: 1283, word: "Care", meaning: "Bakım, Önemsemek", level: "A2" },
    { id: 1284, word: "Career", meaning: "Kariyer", level: "A2" },
    { id: 1285, word: "Careful", meaning: "Dikkatli", level: "A2" },
    { id: 1286, word: "Carefully", meaning: "Dikkatle", level: "A2" },
    { id: 1287, word: "Careless", meaning: "Dikkatsiz", level: "B1" },
    { id: 1288, word: "Carpet", meaning: "Halı", level: "A2" },
    { id: 1289, word: "Carrot", meaning: "Havuç", level: "A2" },
    { id: 1290, word: "Carry", meaning: "Taşımak", level: "A2" },
    { id: 1291, word: "Case", meaning: "Durum, Dava", level: "A2" },
    { id: 1292, word: "Cash", meaning: "Nakit", level: "A2" },
    { id: 1293, word: "Cast", meaning: "Oyuncu kadrosu", level: "B2" },
    { id: 1294, word: "Castle", meaning: "Kale", level: "A2" },
    { id: 1295, word: "Cat", meaning: "Kedi", level: "A2" },
    { id: 1296, word: "Catch", meaning: "Yakalamak", level: "A2" },
    { id: 1297, word: "Category", meaning: "Kategori", level: "B1" },
    { id: 1298, word: "Cause", meaning: "Sebep olmak", level: "A2" },
    { id: 1299, word: "Ceiling", meaning: "Tavan", level: "B1" },
    { id: 1300, word: "Celebrate", meaning: "Kutlamak", level: "A2" },
    { id: 1301, word: "Celebration", meaning: "Kutlama", level: "B1" },
    { id: 1302, word: "Celebrity", meaning: "Ünlü", level: "A2" },
    { id: 1303, word: "Cell", meaning: "Hücre", level: "B2" },
    { id: 1304, word: "Cent", meaning: "Sent", level: "A2" },
    { id: 1305, word: "Center", meaning: "Merkez", level: "A2" },
    { id: 1306, word: "Central", meaning: "Merkezi", level: "B1" },
    { id: 1307, word: "Centre", meaning: "Merkez", level: "A2" },
    { id: 1308, word: "Century", meaning: "Yüzyıl", level: "A2" },
    { id: 1309, word: "Ceremony", meaning: "Tören", level: "B1" },
    { id: 1310, word: "Certain", meaning: "Kesin, Belli", level: "A2" },
    { id: 1311, word: "Certainly", meaning: "Kesinlikle", level: "A2" },
    { id: 1312, word: "Chain", meaning: "Zincir", level: "B1" },
    { id: 1313, word: "Chair", meaning: "Sandalye", level: "A2" },
    { id: 1314, word: "Chairman", meaning: "Başkan (Kurul)", level: "B2" },
    { id: 1315, word: "Challenge", meaning: "Meydan okuma", level: "B1" },
    { id: 1316, word: "Champion", meaning: "Şampiyon", level: "B1" },
    { id: 1317, word: "Chance", meaning: "Şans", level: "A2" },
    { id: 1318, word: "Change", meaning: "Değişim, Değişmek", level: "A2" },
    { id: 1319, word: "Channel", meaning: "Kanal", level: "B1" },
    { id: 1320, word: "Chapter", meaning: "Bölüm", level: "B1" },
    { id: 1321, word: "Character", meaning: "Karakter", level: "A2" },
    { id: 1322, word: "Characteristic", meaning: "Özellik", level: "B2" },
    { id: 1323, word: "Charge", meaning: "Şarj, Ücret", level: "B1" },
    { id: 1324, word: "Charity", meaning: "Hayır kurumu", level: "A2" },
    { id: 1325, word: "Chart", meaning: "Tablo", level: "A2" },
    { id: 1326, word: "Chat", meaning: "Sohbet", level: "A2" },
    { id: 1327, word: "Cheap", meaning: "Ucuz", level: "A2" },
    { id: 1328, word: "Cheat", meaning: "Hile yapmak", level: "B1" },
    { id: 1329, word: "Check", meaning: "Kontrol etmek", level: "A2" },
    { id: 1330, word: "Cheerful", meaning: "Neşeli", level: "B1" },
    { id: 1331, word: "Chemical", meaning: "Kimyasal", level: "B1" },
    { id: 1332, word: "Chemistry", meaning: "Kimya", level: "A2" },
    { id: 1333, word: "Chest", meaning: "Göğüs", level: "B1" },
    { id: 1334, word: "Chicken", meaning: "Tavuk", level: "A2" },
    { id: 1335, word: "Chief", meaning: "Şef", level: "B2" },
    { id: 1336, word: "Child", meaning: "Çocuk", level: "A2" },
    { id: 1337, word: "Childhood", meaning: "Çocukluk", level: "B1" },
    { id: 1338, word: "Chip", meaning: "Çip, Cips", level: "A2" },
    { id: 1339, word: "Chocolate", meaning: "Çikolata", level: "A2" },
    { id: 1340, word: "Choice", meaning: "Seçim", level: "A2" },
    { id: 1341, word: "Choose", meaning: "Seçmek", level: "A2" },
    { id: 1342, word: "Church", meaning: "Kilise", level: "A2" },
    { id: 1343, word: "Cigarette", meaning: "Sigara", level: "A2" },
    { id: 1344, word: "Cinema", meaning: "Sinema", level: "A2" },
    { id: 1345, word: "Circle", meaning: "Daire", level: "A2" },
    { id: 1346, word: "Circumstance", meaning: "Durum, Koşul", level: "B2" },
    { id: 1347, word: "Citizen", meaning: "Vatandaş", level: "B2" },
    { id: 1348, word: "City", meaning: "Şehir", level: "A2" },
    { id: 1349, word: "Civil", meaning: "Sivil", level: "B2" },
    { id: 1350, word: "Claim", meaning: "İddia etmek", level: "B1" },
    { id: 1351, word: "Class", meaning: "Sınıf", level: "A2" },
    { id: 1352, word: "Classic", meaning: "Klasik", level: "B2" },
    { id: 1353, word: "Classroom", meaning: "Sınıf odası", level: "A2" },
    { id: 1354, word: "Clean", meaning: "Temiz", level: "A2" },
    { id: 1355, word: "Clear", meaning: "Açık, Net", level: "A2" },
    { id: 1356, word: "Clearly", meaning: "Açıkça", level: "A2" },
    { id: 1357, word: "Clerk", meaning: "Tezgahtar", level: "B2" },
    { id: 1358, word: "Clever", meaning: "Zeki", level: "A2" },
    { id: 1359, word: "Click", meaning: "Tıklamak", level: "B1" },
    { id: 1360, word: "Client", meaning: "Müşteri", level: "B1" },
    { id: 1361, word: "Climate", meaning: "İklim", level: "A2" },
    { id: 1362, word: "Climb", meaning: "Tırmanmak", level: "A2" },
    { id: 1363, word: "Clock", meaning: "Saat", level: "A2" },
    { id: 1364, word: "Close", meaning: "Kapatmak, Yakın", level: "A2" },
    { id: 1365, word: "Closely", meaning: "Yakından", level: "B2" },
    { id: 1366, word: "Clothes", meaning: "Kıyafetler", level: "A2" },
    { id: 1367, word: "Clothing", meaning: "Giyim", level: "A2" },
    { id: 1368, word: "Cloud", meaning: "Bulut", level: "A2" },
    { id: 1369, word: "Club", meaning: "Kulüp", level: "A2" },
    { id: 1370, word: "Coach", meaning: "Koç", level: "A2" },
    { id: 1371, word: "Coal", meaning: "Kömür", level: "B1" },
    { id: 1372, word: "Coast", meaning: "Sahil", level: "A2" },
    { id: 1373, word: "Coat", meaning: "Mont", level: "A2" },
    { id: 1374, word: "Code", meaning: "Kod", level: "A2" },
    { id: 1375, word: "Coffee", meaning: "Kahve", level: "A2" },
    { id: 1376, word: "Coin", meaning: "Madeni para", level: "B1" },
    { id: 1377, word: "Cold", meaning: "Soğuk", level: "A2" },
    { id: 1378, word: "Collapse", meaning: "Çökmek", level: "B2" },
    { id: 1379, word: "Colleague", meaning: "Meslektaş", level: "A2" },
    { id: 1380, word: "Collect", meaning: "Toplamak", level: "A2" },
    { id: 1381, word: "Collection", meaning: "Koleksiyon", level: "B1" },
    { id: 1382, word: "College", meaning: "Kolej", level: "A2" },
    { id: 1383, word: "Color", meaning: "Renk", level: "A2" },
    { id: 1384, word: "Colour", meaning: "Renk (İng)", level: "A2" },
    { id: 1385, word: "Column", meaning: "Sütun", level: "B1" },
    { id: 1386, word: "Combination", meaning: "Kombinasyon", level: "B2" },
    { id: 1387, word: "Combine", meaning: "Birleştirmek", level: "B1" },
    { id: 1388, word: "Come", meaning: "Gelmek", level: "A2" },
    { id: 1389, word: "Comedy", meaning: "Komedi", level: "A2" },
    { id: 1390, word: "Comfort", meaning: "Rahat", level: "B2" },
    { id: 1391, word: "Comfortable", meaning: "Konforlu", level: "A2" },
    { id: 1392, word: "Command", meaning: "Emir", level: "B2" },
    { id: 1393, word: "Comment", meaning: "Yorum", level: "A2" },
    { id: 1394, word: "Commercial", meaning: "Ticari", level: "B1" },
    { id: 1395, word: "Commission", meaning: "Komisyon", level: "B2" },
    { id: 1396, word: "Commit", meaning: "Adamak, Suç işlemek", level: "B1" },
    { id: 1397, word: "Commitment", meaning: "Bağlılık", level: "B2" },
    { id: 1398, word: "Committee", meaning: "Komite", level: "B2" },
    { id: 1399, word: "Common", meaning: "Yaygın", level: "A2" },
    { id: 1400, word: "Commonly", meaning: "Yaygın olarak", level: "B2" }
