[
    { id: 1401, word: "Communicate", meaning: "İletişim kurmak", level: "A2" },
    { id: 1402, word: "Communication", meaning: "İletişim", level: "B1" },
    { id: 1403, word: "Community", meaning: "Topluluk", level: "A2" },
    { id: 1404, word: "Company", meaning: "Şirket", level: "A2" },
    { id: 1405, word: "Compare", meaning: "Karşılaştırmak", level: "A2" },
    { id: 1406, word: "Comparison", meaning: "Karşılaştırma", level: "B1" },
    { id: 1407, word: "Compete", meaning: "Yarışmak", level: "A2" },
    { id: 1408, word: "Competition", meaning: "Yarışma", level: "A2" },
    { id: 1409, word: "Competitive", meaning: "Rekabetçi", level: "B1" },
    { id: 1410, word: "Complain", meaning: "Şikayet etmek", level: "A2" },
    { id: 1411, word: "Complaint", meaning: "Şikayet", level: "B1" },
    { id: 1412, word: "Complete", meaning: "Tamamlamak", level: "A2" },
    { id: 1413, word: "Completely", meaning: "Tamamen", level: "A2" },
    { id: 1414, word: "Complex", meaning: "Karmaşık", level: "B1" },
    { id: 1415, word: "Complicated", meaning: "Karışık", level: "B2" },
    { id: 1416, word: "Component", meaning: "Bileşen", level: "B2" },
    { id: 1417, word: "Computer", meaning: "Bilgisayar", level: "A2" },
    { id: 1418, word: "Concentrate", meaning: "Konsantre olmak", level: "B1" },
    { id: 1419, word: "Concentration", meaning: "Konsantrasyon", level: "B2" },
    { id: 1420, word: "Concept", meaning: "Kavram", level: "B2" },
    { id: 1421, word: "Concern", meaning: "Endişe", level: "B2" },
    { id: 1422, word: "Concerned", meaning: "Endişeli", level: "B2" },
    { id: 1423, word: "Concert", meaning: "Konser", level: "A2" },
    { id: 1424, word: "Conclude", meaning: "Sonuçlandırmak", level: "B1" },
    { id: 1425, word: "Conclusion", meaning: "Sonuç", level: "B1" },
    { id: 1426, word: "Condition", meaning: "Durum", level: "A2" },
    { id: 1427, word: "Conduct", meaning: "Yönetmek, İletmek", level: "B2" },
    { id: 1428, word: "Conference", meaning: "Konferans", level: "A2" },
    { id: 1429, word: "Confidence", meaning: "Güven", level: "B1" },
    { id: 1430, word: "Confident", meaning: "Kendine güvenen", level: "B1" },
    { id: 1431, word: "Conflict", meaning: "Çatışma", level: "B2" },
    { id: 1432, word: "Confuse", meaning: "Kafasını karıştırmak", level: "B1" },
    { id: 1433, word: "Confused", meaning: "Kafası karışık", level: "B1" },
    { id: 1434, word: "Confusing", meaning: "Kafa karıştırıcı", level: "B1" },
    { id: 1435, word: "Connect", meaning: "Bağlamak", level: "A2" },
    { id: 1436, word: "Connection", meaning: "Bağlantı", level: "B1" },
    { id: 1437, word: "Conscious", meaning: "Bilinçli", level: "B2" },
    { id: 1438, word: "Consequence", meaning: "Sonuç", level: "B1" },
    { id: 1439, word: "Conservative", meaning: "Muhafazakar", level: "B2" },
    { id: 1440, word: "Consider", meaning: "Göz önünde bulundurmak", level: "A2" },
    { id: 1441, word: "Consideration", meaning: "Düşünce, Husus", level: "B2" },
    { id: 1442, word: "Consist", meaning: "Oluşmak", level: "B1" },
    { id: 1443, word: "Consistent", meaning: "Tutarlı", level: "B2" },
    { id: 1444, word: "Constant", meaning: "Sürekli", level: "B2" },
    { id: 1445, word: "Constantly", meaning: "Sürekli olarak", level: "B2" },
    { id: 1446, word: "Construct", meaning: "İnşa etmek", level: "B2" },
    { id: 1447, word: "Construction", meaning: "İnşaat", level: "B1" },
    { id: 1448, word: "Consume", meaning: "Tüketmek", level: "B1" },
    { id: 1449, word: "Consumer", meaning: "Tüketici", level: "B1" },
    { id: 1450, word: "Contact", meaning: "İletişim", level: "A2" },
    { id: 1451, word: "Contain", meaning: "İçermek", level: "A2" },
    { id: 1452, word: "Container", meaning: "Kap, Konteyner", level: "B1" },
    { id: 1453, word: "Contemporary", meaning: "Çağdaş", level: "B2" },
    { id: 1454, word: "Content", meaning: "İçerik", level: "B1" },
    { id: 1455, word: "Contest", meaning: "Yarışma", level: "B2" },
    { id: 1456, word: "Context", meaning: "Bağlam", level: "B2" },
    { id: 1457, word: "Continent", meaning: "Kıta", level: "A2" },
    { id: 1458, word: "Continue", meaning: "Devam etmek", level: "A2" },
    { id: 1459, word: "Continuous", meaning: "Sürekli", level: "B1" },
    { id: 1460, word: "Contract", meaning: "Sözleşme", level: "B1" },
    { id: 1461, word: "Contrast", meaning: "Zıtlık", level: "B1" },
    { id: 1462, word: "Contribute", meaning: "Katkıda bulunmak", level: "B2" },
    { id: 1463, word: "Contribution", meaning: "Katkı", level: "B2" },
    { id: 1464, word: "Control", meaning: "Kontrol", level: "A2" },
    { id: 1465, word: "Convenient", meaning: "Uygun, Elverişli", level: "B1" },
    { id: 1466, word: "Conversation", meaning: "Konuşma", level: "A2" },
    { id: 1467, word: "Convert", meaning: "Dönüştürmek", level: "B2" },
    { id: 1468, word: "Convince", meaning: "İkna etmek", level: "B1" },
    { id: 1469, word: "Cook", meaning: "Pişirmek", level: "A2" },
    { id: 1470, word: "Cooker", meaning: "Ocak", level: "A2" },
    { id: 1471, word: "Cookie", meaning: "Kurabiye", level: "A2" },
    { id: 1472, word: "Cooking", meaning: "Yemek pişirme", level: "A2" },
    { id: 1473, word: "Cool", meaning: "Serin", level: "A2" },
    { id: 1474, word: "Copy", meaning: "Kopyalamak", level: "A2" },
    { id: 1475, word: "Core", meaning: "Çekirdek, Öz", level: "B2" },
    { id: 1476, word: "Corner", meaning: "Köşe", level: "A2" },
    { id: 1477, word: "Corporate", meaning: "Kurumsal", level: "B2" },
    { id: 1478, word: "Correct", meaning: "Doğru", level: "A2" },
    { id: 1479, word: "Cost", meaning: "Maliyet", level: "A2" },
    { id: 1480, word: "Costume", meaning: "Kostüm", level: "B1" },
    { id: 1481, word: "Cottage", meaning: "Kulübe", level: "B1" },
    { id: 1482, word: "Cotton", meaning: "Pamuk", level: "B1" },
    { id: 1483, word: "Cough", meaning: "Öksürmek", level: "B1" },
    { id: 1484, word: "Council", meaning: "Konsey", level: "B2" },
    { id: 1485, word: "Count", meaning: "Saymak", level: "A2" },
    { id: 1486, word: "Counter", meaning: "Tezgah", level: "B1" },
    { id: 1487, word: "Country", meaning: "Ülke", level: "A2" },
    { id: 1488, word: "Countryside", meaning: "Kırsal bölge", level: "B1" },
    { id: 1489, word: "County", meaning: "İlçe", level: "B2" },
    { id: 1490, word: "Couple", meaning: "Çift", level: "A2" },
    { id: 1491, word: "Courage", meaning: "Cesaret", level: "B2" },
    { id: 1492, word: "Course", meaning: "Kurs, Ders", level: "A2" },
    { id: 1493, word: "Court", meaning: "Mahkeme", level: "B1" },
    { id: 1494, word: "Cousin", meaning: "Kuzen", level: "A2" },
    { id: 1495, word: "Cover", meaning: "Kaplamak", level: "A2" },
    { id: 1496, word: "Covered", meaning: "Kaplı", level: "B1" },
    { id: 1497, word: "Cow", meaning: "İnek", level: "A2" },
    { id: 1498, word: "Crash", meaning: "Çarpmak", level: "B1" },
    { id: 1499, word: "Crazy", meaning: "Çılgın", level: "A2" },
    { id: 1500, word: "Cream", meaning: "Krema", level: "A2" },
    { id: 1501, word: "Create", meaning: "Yaratmak", level: "A2" },
    { id: 1502, word: "Creation", meaning: "Yaratılış", level: "B2" },
    { id: 1503, word: "Creative", meaning: "Yaratıcı", level: "A2" },
    { id: 1504, word: "Creature", meaning: "Yaratık", level: "B2" },
    { id: 1505, word: "Credit", meaning: "Kredi", level: "B1" },
    { id: 1506, word: "Crew", meaning: "Mürettebat", level: "B1" },
    { id: 1507, word: "Crime", meaning: "Suç", level: "A2" },
    { id: 1508, word: "Criminal", meaning: "Suçlu", level: "A2" },
    { id: 1509, word: "Crisis", meaning: "Kriz", level: "B2" },
    { id: 1510, word: "Criterion", meaning: "Kriter", level: "B2" },
    { id: 1511, word: "Critic", meaning: "Eleştirmen", level: "B2" },
    { id: 1512, word: "Critical", meaning: "Kritik", level: "B2" },
    { id: 1513, word: "Criticism", meaning: "Eleştiri", level: "B2" },
    { id: 1514, word: "Criticize", meaning: "Eleştirmek", level: "B2" },
    { id: 1515, word: "Crop", meaning: "Mahsul", level: "B2" },
    { id: 1516, word: "Cross", meaning: "Geçmek (karşıya)", level: "A2" },
    { id: 1517, word: "Crowd", meaning: "Kalabalık", level: "A2" },
    { id: 1518, word: "Crowded", meaning: "Kalabalık", level: "A2" },
    { id: 1519, word: "Crucial", meaning: "Çok önemli", level: "B2" },
    { id: 1520, word: "Cruel", meaning: "Zalim", level: "B1" },
    { id: 1521, word: "Cry", meaning: "Ağlamak", level: "A2" },
    { id: 1522, word: "Cultural", meaning: "Kültürel", level: "B1" },
    { id: 1523, word: "Culture", meaning: "Kültür", level: "B1" },
    { id: 1524, word: "Cup", meaning: "Fincan", level: "A2" },
    { id: 1525, word: "Cupboard", meaning: "Dolap", level: "A2" },
    { id: 1526, word: "Cure", meaning: "Tedavi etmek", level: "B2" },
    { id: 1527, word: "Curly", meaning: "Kıvırcık", level: "A2" },
    { id: 1528, word: "Currency", meaning: "Para birimi", level: "B1" },
    { id: 1529, word: "Current", meaning: "Mevcut", level: "B1" },
    { id: 1530, word: "Currently", meaning: "Şu anda", level: "B1" },
    { id: 1531, word: "Curtain", meaning: "Perde", level: "B1" },
    { id: 1532, word: "Curve", meaning: "Eğri", level: "B2" },
    { id: 1533, word: "Curved", meaning: "Kavisli", level: "B2" },
    { id: 1534, word: "Custom", meaning: "Gelenek", level: "B1" },
    { id: 1535, word: "Customer", meaning: "Müşteri", level: "A2" },
    { id: 1536, word: "Cut", meaning: "Kesmek", level: "A2" },
    { id: 1537, word: "Cycle", meaning: "Bisiklete binmek", level: "A2" },
    { id: 1538, word: "Dad", meaning: "Baba", level: "A2" },
    { id: 1539, word: "Daily", meaning: "Günlük", level: "A2" },
    { id: 1540, word: "Damage", meaning: "Hasar", level: "B1" },
    { id: 1541, word: "Dance", meaning: "Dans etmek", level: "A2" },
    { id: 1542, word: "Dancer", meaning: "Dansçı", level: "A2" },
    { id: 1543, word: "Dancing", meaning: "Dans", level: "A2" },
    { id: 1544, word: "Danger", meaning: "Tehlike", level: "A2" },
    { id: 1545, word: "Dangerous", meaning: "Tehlikeli", level: "A2" },
    { id: 1546, word: "Dark", meaning: "Karanlık", level: "A2" },
    { id: 1547, word: "Data", meaning: "Veri", level: "A2" },
    { id: 1548, word: "Date", meaning: "Tarih, Hurma", level: "A2" },
    { id: 1549, word: "Daughter", meaning: "Kız evlat", level: "A2" },
    { id: 1550, word: "Dead", meaning: "Ölü", level: "B1" },
    { id: 1551, word: "Deal", meaning: "Anlaşma", level: "B1" },
    { id: 1552, word: "Dear", meaning: "Sevgili", level: "A2" },
    { id: 1553, word: "Death", meaning: "Ölüm", level: "B1" },
    { id: 1554, word: "Debate", meaning: "Tartışma", level: "B2" },
    { id: 1555, word: "Debt", meaning: "Borç", level: "B2" },
    { id: 1556, word: "Decade", meaning: "On yıl", level: "B1" },
    { id: 1557, word: "December", meaning: "Aralık", level: "A2" },
    { id: 1558, word: "Deep", meaning: "Derin", level: "A2" },
    { id: 1559, word: "Degree", meaning: "Derece", level: "A2" },
    { id: 1560, word: "Dentist", meaning: "Dişçi", level: "A2" },
    { id: 1561, word: "Department", meaning: "Bölüm", level: "A2" },
    { id: 1562, word: "Depend", meaning: "Bağlı olmak", level: "A2" },
    { id: 1563, word: "Desert", meaning: "Çöl", level: "A2" },
    { id: 1564, word: "Designer", meaning: "Tasarımcı", level: "A2" },
    { id: 1565, word: "Destroy", meaning: "Yok etmek", level: "A2" },
    { id: 1566, word: "Detective", meaning: "Dedektif", level: "A2" },
    { id: 1567, word: "Develop", meaning: "Geliştirmek", level: "A2" },
    { id: 1568, word: "Device", meaning: "Cihaz", level: "A2" },
    { id: 1569, word: "Diary", meaning: "Günlük", level: "A2" },
    { id: 1570, word: "Differently", meaning: "Farklı şekilde", level: "A2" },
    { id: 1571, word: "Digital", meaning: "Dijital", level: "A2" },
    { id: 1572, word: "Direct", meaning: "Doğrudan", level: "A2" },
    { id: 1573, word: "Direction", meaning: "Yön", level: "A2" },
    { id: 1574, word: "Director", meaning: "Yönetmen", level: "A2" },
    { id: 1575, word: "Disagree", meaning: "Katılmamak", level: "A2" },
    { id: 1576, word: "Disappear", meaning: "Gözden kaybolmak", level: "A2" },
    { id: 1577, word: "Disaster", meaning: "Felaket", level: "A2" },
    { id: 1578, word: "Discover", meaning: "Keşfetmek", level: "A2" },
    { id: 1579, word: "Discovery", meaning: "Keşif", level: "A2" },
    { id: 1580, word: "Discussion", meaning: "Tartışma", level: "A2" },
    { id: 1581, word: "Disease", meaning: "Hastalık", level: "A2" },
    { id: 1582, word: "Distance", meaning: "Mesafe", level: "A2" },
    { id: 1583, word: "Divorced", meaning: "Boşanmış", level: "A2" },
    { id: 1584, word: "Document", meaning: "Belge", level: "A2" },
    { id: 1585, word: "Double", meaning: "Çift", level: "A2" },
    { id: 1586, word: "Download", meaning: "İndirmek", level: "A2" },
    { id: 1587, word: "Downstairs", meaning: "Alt kat", level: "A2" },
    { id: 1588, word: "Drama", meaning: "Dram", level: "A2" },
    { id: 1589, word: "Drawing", meaning: "Çizim", level: "A2" },
    { id: 1590, word: "Dream", meaning: "Rüya", level: "A2" },
    { id: 1591, word: "Drive", meaning: "Sürmek", level: "A2" },
    { id: 1592, word: "Driving", meaning: "Sürüş", level: "A2" },
    { id: 1593, word: "Drop", meaning: "Düşürmek", level: "A2" },
    { id: 1594, word: "Drug", meaning: "İlaç", level: "A2" },
    { id: 1595, word: "Dry", meaning: "Kuru", level: "A2" },
    { id: 1596, word: "Earn", meaning: "Kazanmak (Para)", level: "A2" },
    { id: 1597, word: "Earth", meaning: "Dünya", level: "A2" },
    { id: 1598, word: "Easily", meaning: "Kolayca", level: "A2" },
    { id: 1599, word: "Education", meaning: "Eğitim", level: "A2" },
    { id: 1600, word: "Effect", meaning: "Etki", level: "A2" }
];
