[
    { id: 2801, word: "Profit", meaning: "Kâr", level: "B1" },
    { id: 2802, word: "Program", meaning: "Program", level: "A2" },
    { id: 2803, word: "Programme", meaning: "Program (İng)", level: "A2" },
    { id: 2804, word: "Progress", meaning: "İlerleme", level: "B1" },
    { id: 2805, word: "Project", meaning: "Proje", level: "A2" },
    { id: 2806, word: "Promise", meaning: "Söz vermek", level: "A2" },
    { id: 2807, word: "Promote", meaning: "Desteklemek, Terfi ettirmek", level: "B1" },
    { id: 2808, word: "Promotion", meaning: "Tanıtım, Terfi", level: "B1" },
    { id: 2809, word: "Prompt", meaning: "Çabuk, Teşvik etmek", level: "B2" },
    { id: 2810, word: "Pronounce", meaning: "Telaffuz etmek", level: "A2" },
    { id: 2811, word: "Proof", meaning: "Kanıt", level: "B1" },
    { id: 2812, word: "Proper", meaning: "Uygun", level: "B1" },
    { id: 2813, word: "Properly", meaning: "Düzgünce", level: "B1" },
    { id: 2814, word: "Property", meaning: "Mülk, Özellik", level: "B1" },
    { id: 2815, word: "Proportion", meaning: "Oran", level: "B2" },
    { id: 2816, word: "Proposal", meaning: "Teklif", level: "B2" },
    { id: 2817, word: "Propose", meaning: "Teklif etmek", level: "B1" },
    { id: 2818, word: "Prospect", meaning: "Olasılık, Beklenti", level: "B2" },
    { id: 2819, word: "Protect", meaning: "Korumak", level: "A2" },
    { id: 2820, word: "Protection", meaning: "Koruma", level: "B1" },
    { id: 2821, word: "Protein", meaning: "Protein", level: "B1" },
    { id: 2822, word: "Protest", meaning: "Protesto", level: "B1" },
    { id: 2823, word: "Proud", meaning: "Gururlu", level: "A2" },
    { id: 2824, word: "Prove", meaning: "Kanıtlamak", level: "B1" },
    { id: 2825, word: "Provide", meaning: "Sağlamak", level: "A2" },
    { id: 2826, word: "Psychological", meaning: "Psikolojik", level: "B2" },
    { id: 2827, word: "Psychology", meaning: "Psikoloji", level: "B2" },
    { id: 2828, word: "Public", meaning: "Halk, Kamu", level: "A2" },
    { id: 2829, word: "Publication", meaning: "Yayın", level: "B2" },
    { id: 2830, word: "Publicly", meaning: "Halka açıkça", level: "B2" },
    { id: 2831, word: "Publish", meaning: "Yayınlamak", level: "B1" },
    { id: 2832, word: "Publisher", meaning: "Yayıncı", level: "B2" },
    { id: 2833, word: "Pull", meaning: "Çekmek", level: "A2" },
    { id: 2834, word: "Pump", meaning: "Pompa", level: "B1" },
    { id: 2835, word: "Punch", meaning: "Yumruklamak", level: "B2" },
    { id: 2836, word: "Punish", meaning: "Cezalandırmak", level: "B1" },
    { id: 2837, word: "Punishment", meaning: "Ceza", level: "B1" },
    { id: 2838, word: "Pupil", meaning: "Öğrenci, Gözbebeği", level: "B1" },
    { id: 2839, word: "Purchase", meaning: "Satın almak", level: "B1" },
    { id: 2840, word: "Pure", meaning: "Saf", level: "B1" },
    { id: 2841, word: "Purely", meaning: "Sırf, Tamamen", level: "B2" },
    { id: 2842, word: "Purple", meaning: "Mor", level: "A2" },
    { id: 2843, word: "Purpose", meaning: "Amaç", level: "A2" },
    { id: 2844, word: "Pursue", meaning: "Peşinden koşmak", level: "B2" },
    { id: 2845, word: "Push", meaning: "İtmek", level: "A2" },
    { id: 2846, word: "Put", meaning: "Koymak", level: "A2" },
    { id: 2847, word: "Qualification", meaning: "Nitelik", level: "B1" },
    { id: 2848, word: "Qualified", meaning: "Nitelikli", level: "B2" },
    { id: 2849, word: "Quality", meaning: "Kalite", level: "A2" },
    { id: 2850, word: "Quantity", meaning: "Miktar", level: "B1" },
    { id: 2851, word: "Quarter", meaning: "Çeyrek", level: "A2" },
    { id: 2852, word: "Queen", meaning: "Kraliçe", level: "A2" },
    { id: 2853, word: "Question", meaning: "Soru", level: "A2" },
    { id: 2854, word: "Quick", meaning: "Hızlı", level: "A2" },
    { id: 2855, word: "Quickly", meaning: "Hızlıca", level: "A2" },
    { id: 2856, word: "Quiet", meaning: "Sessiz", level: "A2" },
    { id: 2857, word: "Quietly", meaning: "Sessizce", level: "A2" },
    { id: 2858, word: "Quit", meaning: "Vazgeçmek, Çıkmak", level: "B1" },
    { id: 2859, word: "Quite", meaning: "Epey, Oldukça", level: "A2" },
    { id: 2860, word: "Quote", meaning: "Alıntı", level: "B2" },
    { id: 2861, word: "Race", meaning: "Yarış, Irk", level: "A2" },
    { id: 2862, word: "Racing", meaning: "Yarış", level: "A2" },
    { id: 2863, word: "Radical", meaning: "Radikal", level: "C1" },
    { id: 2864, word: "Radio", meaning: "Radyo", level: "A2" },
    { id: 2865, word: "Rail", meaning: "Ray", level: "B1" },
    { id: 2866, word: "Railway", meaning: "Demiryolu", level: "A2" },
    { id: 2867, word: "Rain", meaning: "Yağmur", level: "A2" },
    { id: 2868, word: "Raise", meaning: "Kaldırmak, Artırmak", level: "A2" },
    { id: 2869, word: "Range", meaning: "Menzil, Çeşit", level: "B1" },
    { id: 2870, word: "Rank", meaning: "Rütbe, Sıra", level: "B2" },
    { id: 2871, word: "Rapid", meaning: "Hızlı", level: "B2" },
    { id: 2872, word: "Rapidly", meaning: "Hızla", level: "B2" },
    { id: 2873, word: "Rare", meaning: "Nadir", level: "B1" },
    { id: 2874, word: "Rarely", meaning: "Nadiren", level: "B1" },
    { id: 2875, word: "Rate", meaning: "Oran", level: "B1" },
    { id: 2876, word: "Rather", meaning: "Oldukça, Tercihen", level: "A2" },
    { id: 2877, word: "Raw", meaning: "Çiğ", level: "B2" },
    { id: 2878, word: "Reach", meaning: "Ulaşmak", level: "A2" },
    { id: 2879, word: "React", meaning: "Tepki vermek", level: "B1" },
    { id: 2880, word: "Reaction", meaning: "Tepki", level: "B1" },
    { id: 2881, word: "Read", meaning: "Okumak", level: "A2" },
    { id: 2882, word: "Reader", meaning: "Okuyucu", level: "A2" },
    { id: 2883, word: "Reading", meaning: "Okuma", level: "A2" },
    { id: 2884, word: "Ready", meaning: "Hazır", level: "A2" },
    { id: 2885, word: "Real", meaning: "Gerçek", level: "A2" },
    { id: 2886, word: "Realistic", meaning: "Gerçekçi", level: "B2" },
    { id: 2887, word: "Reality", meaning: "Gerçeklik", level: "B1" },
    { id: 2888, word: "Realize", meaning: "Fark etmek", level: "A2" },
    { id: 2889, word: "Really", meaning: "Gerçekten", level: "A2" },
    { id: 2890, word: "Rear", meaning: "Arka", level: "B2" },
    { id: 2891, word: "Reason", meaning: "Sebep", level: "A2" },
    { id: 2892, word: "Reasonable", meaning: "Makul", level: "B1" },
    { id: 2893, word: "Recall", meaning: "Hatırlamak", level: "B2" },
    { id: 2894, word: "Receipt", meaning: "Fiş, Makbuz", level: "B1" },
    { id: 2895, word: "Receive", meaning: "Teslim almak", level: "A2" },
    { id: 2896, word: "Recent", meaning: "Son, Yeni", level: "A2" },
    { id: 2897, word: "Recently", meaning: "Son zamanlarda", level: "A2" },
    { id: 2898, word: "Reception", meaning: "Resepsiyon", level: "A2" },
    { id: 2899, word: "Recipe", meaning: "Yemek tarifi", level: "A2" },
    { id: 2900, word: "Recognise", meaning: "Tanımak", level: "A2" },
    { id: 2901, word: "Recognition", meaning: "Tanınma", level: "B2" },
    { id: 2902, word: "Recommend", meaning: "Önermek", level: "A2" },
    { id: 2903, word: "Recommendation", meaning: "Öneri", level: "B2" },
    { id: 2904, word: "Record", meaning: "Kayıt", level: "A2" },
    { id: 2905, word: "Recording", meaning: "Kayıt etme", level: "A2" },
    { id: 2906, word: "Recover", meaning: "İyileşmek", level: "B1" },
    { id: 2907, word: "Recovery", meaning: "İyileşme", level: "B2" },
    { id: 2908, word: "Red", meaning: "Kırmızı", level: "A2" },
    { id: 2909, word: "Reduce", meaning: "Azaltmak", level: "A2" },
    { id: 2910, word: "Reduction", meaning: "Azalma", level: "B2" },
    { id: 2911, word: "Refer", meaning: "Atıfta bulunmak", level: "B1" },
    { id: 2912, word: "Reference", meaning: "Referans", level: "B1" },
    { id: 2913, word: "Reflect", meaning: "Yansıtmak", level: "B2" },
    { id: 2914, word: "Reflection", meaning: "Yansıma", level: "B2" },
    { id: 2915, word: "Reform", meaning: "Reform", level: "B2" },
    { id: 2916, word: "Refrigerator", meaning: "Buzdolabı", level: "A2" },
    { id: 2917, word: "Refuse", meaning: "Reddetmek", level: "A2" },
    { id: 2918, word: "Regard", meaning: "Saygı, Bakım", level: "B1" },
    { id: 2919, word: "Region", meaning: "Bölge", level: "A2" },
    { id: 2920, word: "Regional", meaning: "Bölgesel", level: "B1" },
    { id: 2921, word: "Register", meaning: "Kayıt olmak", level: "B1" },
    { id: 2922, word: "Registration", meaning: "Kayıt", level: "B2" },
    { id: 2923, word: "Regret", meaning: "Pişmanlık", level: "B1" },
    { id: 2924, word: "Regular", meaning: "Düzenli", level: "A2" },
    { id: 2925, word: "Regularly", meaning: "Düzenli olarak", level: "B1" },
    { id: 2926, word: "Regulation", meaning: "Yönetmelik", level: "B2" },
    { id: 2927, word: "Reject", meaning: "Reddetmek", level: "B1" },
    { id: 2928, word: "Relate", meaning: "İlişkilendirmek", level: "B1" },
    { id: 2929, word: "Related", meaning: "İlişkili", level: "B1" },
    { id: 2930, word: "Relation", meaning: "İlişki", level: "B1" },
    { id: 2931, word: "Relationship", meaning: "İlişki", level: "B1" },
    { id: 2932, word: "Relative", meaning: "Akraba, Görece", level: "B1" },
    { id: 2933, word: "Relatively", meaning: "Nispeten", level: "B2" },
    { id: 2934, word: "Relax", meaning: "Rahatlamak", level: "A2" },
    { id: 2935, word: "Relaxation", meaning: "Gevşeme", level: "B2" },
    { id: 2936, word: "Relaxed", meaning: "Rahatlamış", level: "B1" },
    { id: 2937, word: "Relaxing", meaning: "Rahatlatıcı", level: "B1" },
    { id: 2938, word: "Release", meaning: "Serbest bırakmak", level: "B1" },
    { id: 2939, word: "Relevant", meaning: "Alakalı", level: "B2" },
    { id: 2940, word: "Reliable", meaning: "Güvenilir", level: "B1" },
    { id: 2941, word: "Relief", meaning: "Rahatlama", level: "B2" },
    { id: 2942, word: "Religion", meaning: "Din", level: "B1" },
    { id: 2943, word: "Religious", meaning: "Dini", level: "B1" },
    { id: 2944, word: "Rely", meaning: "Güvenmek", level: "B2" },
    { id: 2945, word: "Remain", meaning: "Kalmak", level: "B1" },
    { id: 2946, word: "Remaining", meaning: "Kalan", level: "B1" },
    { id: 2947, word: "Remake", meaning: "Yeniden yapmak", level: "B1" },
    { id: 2948, word: "Remark", meaning: "Görüş, Beyan", level: "B2" },
    { id: 2949, word: "Remarkable", meaning: "Dikkat çekici", level: "B2" },
    { id: 2950, word: "Remember", meaning: "Hatırlamak", level: "A2" },
    { id: 2951, word: "Remind", meaning: "Hatırlatmak", level: "B1" },
    { id: 2952, word: "Remote", meaning: "Uzak", level: "B1" },
    { id: 2953, word: "Removal", meaning: "Kaldırma", level: "B2" },
    { id: 2954, word: "Remove", meaning: "Kaldırmak, Çıkarmak", level: "B1" },
    { id: 2955, word: "Rent", meaning: "Kiralamak", level: "A2" },
    { id: 2956, word: "Repair", meaning: "Tamir etmek", level: "A2" },
    { id: 2957, word: "Repeat", meaning: "Tekrarlamak", level: "A2" },
    { id: 2958, word: "Repeated", meaning: "Tekrarlanan", level: "B1" },
    { id: 2959, word: "Replace", meaning: "Yerine koymak", level: "B1" },
    { id: 2960, word: "Reply", meaning: "Cevaplamak", level: "A2" },
    { id: 2961, word: "Report", meaning: "Rapor", level: "A2" },
    { id: 2962, word: "Reporter", meaning: "Muhabir", level: "A2" },
    { id: 2963, word: "Represent", meaning: "Temsil etmek", level: "B1" },
    { id: 2964, word: "Representation", meaning: "Temsil", level: "B2" },
    { id: 2965, word: "Representative", meaning: "Temsilci", level: "B2" },
    { id: 2966, word: "Republic", meaning: "Cumhuriyet", level: "B1" },
    { id: 2967, word: "Reputation", meaning: "İtibar", level: "B2" },
    { id: 2968, word: "Request", meaning: "Rica etmek", level: "A2" },
    { id: 2969, word: "Requirement", meaning: "Gereksinim", level: "B1" },
    { id: 2970, word: "Rescue", meaning: "Kurtarmak", level: "B1" },
    { id: 2971, word: "Research", meaning: "Araştırma", level: "A2" },
    { id: 2972, word: "Researcher", meaning: "Araştırmacı", level: "B1" },
    { id: 2973, word: "Reservation", meaning: "Rezervasyon", level: "A2" },
    { id: 2974, word: "Reserve", meaning: "Ayırmak, Rezerv", level: "B1" },
    { id: 2975, word: "Resident", meaning: "Sakin (bir yerde oturan)", level: "B2" },
    { id: 2976, word: "Resist", meaning: "Direnç göstermek", level: "B2" },
    { id: 2977, word: "Resistance", meaning: "Direnç", level: "B2" },
    { id: 2978, word: "Resolution", meaning: "Karar, Çözünürlük", level: "B2" },
    { id: 2979, word: "Resolve", meaning: "Çözmek", level: "B2" },
    { id: 2980, word: "Resort", meaning: "Tatil yeri", level: "B1" },
    { id: 2981, word: "Resource", meaning: "Kaynak", level: "B1" },
    { id: 2982, word: "Respect", meaning: "Saygı", level: "B1" },
    { id: 2983, word: "Respond", meaning: "Yanıtlamak", level: "B1" },
    { id: 2984, word: "Response", meaning: "Cevap", level: "B1" },
    { id: 2985, word: "Responsibility", meaning: "Sorumluluk", level: "B1" },
    { id: 2986, word: "Responsible", meaning: "Sorumlu", level: "B1" },
    { id: 2987, word: "Rest", meaning: "Dinlenmek", level: "A2" },
    { id: 2988, word: "Restaurant", meaning: "Restoran", level: "A2" },
    { id: 2989, word: "Restore", meaning: "Yenilemek", level: "B2" },
    { id: 2990, word: "Restrict", meaning: "Kısıtlamak", level: "B2" },
    { id: 2991, word: "Restriction", meaning: "Kısıtlama", level: "B2" },
    { id: 2992, word: "Result", meaning: "Sonuç", level: "A2" },
    { id: 2993, word: "Retire", meaning: "Emekli olmak", level: "B1" },
    { id: 2994, word: "Retired", meaning: "Emekli", level: "B1" },
    { id: 2995, word: "Retirement", meaning: "Emeklilik", level: "B1" },
    { id: 2996, word: "Return", meaning: "Geri dönmek", level: "A2" },
    { id: 2997, word: "Reveal", meaning: "Açığa çıkarmak", level: "B2" },
    { id: 2998, word: "Revenue", meaning: "Gelir", level: "B2" },
    { id: 2999, word: "Review", meaning: "Gözden geçirmey, İnceleme", level: "A2" },
    { id: 3000, word: "Revision", meaning: "Revizyon", level: "B1" },
    { id: 3001, word: "Revolution", meaning: "Devrim", level: "B1" },
    { id: 3002, word: "Reward", meaning: "Ödül", level: "B1" },
    { id: 3003, word: "Rhythm", meaning: "Ritim", level: "B2" },
    { id: 3004, word: "Rice", meaning: "Pirinç", level: "A2" },
    { id: 3005, word: "Rich", meaning: "Zengin", level: "A2" },
    { id: 3006, word: "Rid", meaning: "Kurtulmak", level: "B1" },
    { id: 3007, word: "Ride", meaning: "Binmek", level: "A2" },
    { id: 3008, word: "Rider", meaning: "Sürücü", level: "B1" },
    { id: 3009, word: "Ridiculous", meaning: "Gülünç", level: "B2" },
    { id: 3010, word: "Right", meaning: "Doğru, Sağ", level: "A2" },
    { id: 3011, word: "Ring", meaning: "Yüzük, Çalmak", level: "A2" },
    { id: 3012, word: "Rise", meaning: "Yükselmek", level: "A2" },
    { id: 3013, word: "Risk", meaning: "Risk", level: "B1" },
    { id: 3014, word: "River", meaning: "Nehir", level: "A2" },
    { id: 3015, word: "Road", meaning: "Yol", level: "A2" },
    { id: 3016, word: "Rob", meaning: "Soymak", level: "B1" },
    { id: 3017, word: "Robot", meaning: "Robot", level: "A2" },
    { id: 3018, word: "Rock", meaning: "Kaya, Rock (Müzik)", level: "A2" },
    { id: 3019, word: "Role", meaning: "Rol", level: "B1" },
    { id: 3020, word: "Roll", meaning: "Yuvarlanmak", level: "B1" },
    { id: 3021, word: "Romantic", meaning: "Romantik", level: "A2" },
    { id: 3022, word: "Roof", meaning: "Çatı", level: "A2" },
    { id: 3023, word: "Room", meaning: "Oda", level: "A2" },
    { id: 3024, word: "Root", meaning: "Kök", level: "B2" },
    { id: 3025, word: "Rope", meaning: "İp", level: "B1" },
    { id: 3026, word: "Rough", meaning: "Kaba, Engebeli", level: "B1" },
    { id: 3027, word: "Roughly", meaning: "Kabaca", level: "B1" },
    { id: 3028, word: "Round", meaning: "Yuvarlak", level: "A2" },
    { id: 3029, word: "Route", meaning: "Rota", level: "B1" },
    { id: 3030, word: "Routine", meaning: "Rutin", level: "A2" },
    { id: 3031, word: "Row", meaning: "Sıra, Kürek çekmek", level: "B1" },
    { id: 3032, word: "Royal", meaning: "Kraliyet", level: "B1" },
    { id: 3033, word: "Rub", meaning: "Oğalamak", level: "B2" },
    { id: 3034, word: "Rubber", meaning: "Lastik, Silgi", level: "B1" },
    { id: 3035, word: "Rubbish", meaning: "Çöp", level: "A2" },
    { id: 3036, word: "Rude", meaning: "Kaba", level: "B1" },
    { id: 3037, word: "Rugby", meaning: "Ragbi", level: "A2" },
    { id: 3038, word: "Rule", meaning: "Kural", level: "A2" },
    { id: 3039, word: "Ruler", meaning: "Cetvel, Hükümdar", level: "A2" },
    { id: 3040, word: "Run", meaning: "Koşmak", level: "A2" },
    { id: 3041, word: "Runner", meaning: "Koşucu", level: "A2" },
    { id: 3042, word: "Running", meaning: "Koşu", level: "A2" },
    { id: 3043, word: "Rural", meaning: "Kırsal", level: "B2" },
    { id: 3044, word: "Rush", meaning: "Acele etmek", level: "B2" },
    { id: 3045, word: "Sacred", meaning: "Kutsal", level: "C1" },
    { id: 3046, word: "Sad", meaning: "Üzgün", level: "A2" },
    { id: 3047, word: "Sadly", meaning: "Maalesef", level: "A2" },
    { id: 3048, word: "Safe", meaning: "Güvenli", level: "A2" },
    { id: 3049, word: "Safety", meaning: "Güvenlik", level: "B1" },
    { id: 3050, word: "Sail", meaning: "Yelken açmak", level: "A2" },
    { id: 3051, word: "Sailing", meaning: "Yelkencilik", level: "A2" },
    { id: 3052, word: "Sailor", meaning: "Denizci", level: "B1" },
    { id: 3053, word: "Salad", meaning: "Salata", level: "A2" },
    { id: 3054, word: "Salary", meaning: "Maaş", level: "B1" },
    { id: 3055, word: "Sale", meaning: "Satış", level: "A2" },
    { id: 3056, word: "Salt", meaning: "Tuz", level: "A2" },
    { id: 3057, word: "Same", meaning: "Aynı", level: "A2" },
    { id: 3058, word: "Sample", meaning: "Örnek", level: "B1" },
    { id: 3059, word: "Sand", meaning: "Kum", level: "A2" },
    { id: 3060, word: "Sandwich", meaning: "Sandviç", level: "A2" },
    { id: 3061, word: "Satellite", meaning: "Uydu", level: "B2" },
    { id: 3062, word: "Satisfaction", meaning: "Memnuniyet", level: "B2" },
    { id: 3063, word: "Satisfied", meaning: "Memnun", level: "B2" },
    { id: 3064, word: "Satisfy", meaning: "Tatmin etmek", level: "B1" },
    { id: 3065, word: "Saturday", meaning: "Cumartesi", level: "A2" },
    { id: 3066, word: "Sauce", meaning: "Sos", level: "A2" },
    { id: 3067, word: "Sausage", meaning: "Sosis", level: "A2" },
    { id: 3068, word: "Save", meaning: "Kaydetmek, Kurtarmak", level: "A2" },
    { id: 3069, word: "Saving", meaning: "Tasarruf", level: "B1" },
    { id: 3070, word: "Say", meaning: "Söylemek", level: "A2" },
    { id: 3071, word: "Scale", meaning: "Ölçek", level: "B1" },
    { id: 3072, word: "Scared", meaning: "Korkmuş", level: "A2" },
    { id: 3073, word: "Scary", meaning: "Korkutucu", level: "A2" },
    { id: 3074, word: "Scene", meaning: "Sahne", level: "A2" },
    { id: 3075, word: "Schedule", meaning: "Program, Takvim", level: "B1" },
    { id: 3076, word: "Scheme", meaning: "Plan, Tasarı", level: "B2" },
    { id: 3077, word: "School", meaning: "Okul", level: "A2" },
    { id: 3078, word: "Science", meaning: "Bilim", level: "A2" },
    { id: 3079, word: "Scientific", meaning: "Bilimsel", level: "B1" },
    { id: 3080, word: "Scientist", meaning: "Bilim insanı", level: "A2" },
    { id: 3081, word: "Scissors", meaning: "Makas", level: "B1" },
    { id: 3082, word: "Score", meaning: "Skor", level: "A2" },
    { id: 3083, word: "Scream", meaning: "Çığlık atmak", level: "B1" },
    { id: 3084, word: "Screen", meaning: "Ekran", level: "A2" },
    { id: 3085, word: "Script", meaning: "Senaryo", level: "B1" },
    { id: 3086, word: "Sea", meaning: "Deniz", level: "A2" },
    { id: 3087, word: "Seal", meaning: "Mühürlemek, Fok", level: "B2" },
    { id: 3088, word: "Search", meaning: "Aramak", level: "A2" },
    { id: 3089, word: "Season", meaning: "Mevsim", level: "A2" },
    { id: 3090, word: "Seat", meaning: "Koltuk", level: "A2" },
    { id: 3091, word: "Second", meaning: "İkinci", level: "A2" },
    { id: 3092, word: "Secondary", meaning: "İkincil, Ortaokul", level: "B1" },
    { id: 3093, word: "Secret", meaning: "Sır", level: "A2" },
    { id: 3094, word: "Secretary", meaning: "Sekreter", level: "A2" },
    { id: 3095, word: "Section", meaning: "Bölüm", level: "A2" },
    { id: 3096, word: "Sector", meaning: "Sektör", level: "B1" },
    { id: 3097, word: "Secure", meaning: "Güvenli", level: "B2" },
    { id: 3098, word: "Security", meaning: "Güvenlik", level: "B1" },
    { id: 3099, word: "See", meaning: "Görmek", level: "A2" },
    { id: 3100, word: "Seed", meaning: "Tohum", level: "B1" }
];
