[
    { id: 1901, word: "Gentleman", meaning: "Beyefendi", level: "B1" },
    { id: 1902, word: "Geography", meaning: "Coğrafya", level: "A2" },
    { id: 1903, word: "Get", meaning: "Almak", level: "A2" },
    { id: 1904, word: "Ghost", meaning: "Hayalet", level: "B1" },
    { id: 1905, word: "Giant", meaning: "Dev", level: "B1" },
    { id: 1906, word: "Gift", meaning: "Hediye", level: "A2" },
    { id: 1907, word: "Girl", meaning: "Kız", level: "A2" },
    { id: 1908, word: "Girlfriend", meaning: "Kız arkadaş", level: "A2" },
    { id: 1909, word: "Give", meaning: "Vermek", level: "A2" },
    { id: 1910, word: "Glad", meaning: "Memnun", level: "B1" },
    { id: 1911, word: "Glass", meaning: "Bardak, Cam", level: "A2" },
    { id: 1912, word: "Global", meaning: "Küresel", level: "B1" },
    { id: 1913, word: "Glove", meaning: "Eldiven", level: "B1" },
    { id: 1914, word: "Go", meaning: "Gitmek", level: "A2" },
    { id: 1915, word: "Goal", meaning: "Hedef", level: "A2" },
    { id: 1916, word: "God", meaning: "Tanrı", level: "A2" },
    { id: 1917, word: "Gold", meaning: "Altın", level: "A2" },
    { id: 1918, word: "Golf", meaning: "Golf", level: "A2" },
    { id: 1919, word: "Good", meaning: "İyi", level: "A2" },
    { id: 1920, word: "Goodbye", meaning: "Hoşçakal", level: "A2" },
    { id: 1921, word: "Goods", meaning: "Mallar", level: "B2" },
    { id: 1922, word: "Govern", meaning: "Yönetmek", level: "B2" },
    { id: 1923, word: "Government", meaning: "Hükümet", level: "A2" },
    { id: 1924, word: "Grab", meaning: "Kapmak", level: "B2" },
    { id: 1925, word: "Grade", meaning: "Not, Derece", level: "B1" },
    { id: 1926, word: "Gradually", meaning: "Giderek", level: "B2" },
    { id: 1927, word: "Graduate", meaning: "Mezun olmak", level: "B1" },
    { id: 1928, word: "Grain", meaning: "Tahıl", level: "B1" },
    { id: 1929, word: "Grand", meaning: "Büyük, Görkemli", level: "B2" },
    { id: 1930, word: "Grandfather", meaning: "Büyükbaba", level: "A2" },
    { id: 1931, word: "Grandmother", meaning: "Büyükanne", level: "A2" },
    { id: 1932, word: "Grandparent", meaning: "Büyükanne/baba", level: "A2" },
    { id: 1933, word: "Grant", meaning: "Bağışlamak, Onaylamak", level: "B2" },
    { id: 1934, word: "Grass", meaning: "Çim", level: "A2" },
    { id: 1935, word: "Grateful", meaning: "Minnettar", level: "B1" },
    { id: 1936, word: "Great", meaning: "Harika", level: "A2" },
    { id: 1937, word: "Green", meaning: "Yeşil", level: "A2" },
    { id: 1938, word: "Greet", meaning: "Selamlamak", level: "B1" },
    { id: 1939, word: "Grey", meaning: "Gri", level: "A2" },
    { id: 1940, word: "Ground", meaning: "Zemin", level: "A2" },
    { id: 1941, word: "Group", meaning: "Grup", level: "A2" },
    { id: 1942, word: "Grow", meaning: "Büyümek", level: "A2" },
    { id: 1943, word: "Growth", meaning: "Büyüme", level: "B1" },
    { id: 1944, word: "Guarantee", meaning: "Garanti", level: "B2" },
    { id: 1945, word: "Guard", meaning: "Korumak, Nöbetçi", level: "B1" },
    { id: 1946, word: "Guess", meaning: "Tahmin etmek", level: "A2" },
    { id: 1947, word: "Guest", meaning: "Konuk", level: "A2" },
    { id: 1948, word: "Guide", meaning: "Rehber", level: "A2" },
    { id: 1949, word: "Guilty", meaning: "Suçlu", level: "B1" },
    { id: 1950, word: "Guitar", meaning: "Gitar", level: "A2" },
    { id: 1951, word: "Gun", meaning: "Silah", level: "A2" },
    { id: 1952, word: "Guy", meaning: "Adam", level: "A2" },
    { id: 1953, word: "Gym", meaning: "Spor salonu", level: "A2" },
    { id: 1954, word: "Habit", meaning: "Alışkanlık", level: "B1" },
    { id: 1955, word: "Hair", meaning: "Saç", level: "A2" },
    { id: 1956, word: "Half", meaning: "Yarım", level: "A2" },
    { id: 1957, word: "Hall", meaning: "Salon, Hol", level: "A2" },
    { id: 1958, word: "Hand", meaning: "El", level: "A2" },
    { id: 1959, word: "Handle", meaning: "Kulp, Ele almak", level: "B2" },
    { id: 1960, word: "Hang", meaning: "Asmak", level: "B1" },
    { id: 1961, word: "Happen", meaning: "Olmak", level: "A2" },
    { id: 1962, word: "Happily", meaning: "Mutluca", level: "A2" },
    { id: 1963, word: "Happiness", meaning: "Mutluluk", level: "B1" },
    { id: 1964, word: "Happy", meaning: "Mutlu", level: "A2" },
    { id: 1965, word: "Hard", meaning: "Zor, Sert", level: "A2" },
    { id: 1966, word: "Hardly", meaning: "Neredeyse hiç", level: "B1" },
    { id: 1967, word: "Harm", meaning: "Zarar", level: "B2" },
    { id: 1968, word: "Harmful", meaning: "Zararlı", level: "B2" },
    { id: 1969, word: "Hat", meaning: "Şapka", level: "A2" },
    { id: 1970, word: "Hate", meaning: "Nefret etmek", level: "A2" },
    { id: 1971, word: "Have", meaning: "Sahip olmak", level: "A2" },
    { id: 1972, word: "He", meaning: "O (Erkek)", level: "A2" },
    { id: 1973, word: "Head", meaning: "Baş", level: "A2" },
    { id: 1974, word: "Headache", meaning: "Baş ağrısı", level: "A2" },
    { id: 1975, word: "Headline", meaning: "Manşet", level: "B1" },
    { id: 1976, word: "Health", meaning: "Sağlık", level: "A2" },
    { id: 1977, word: "Healthy", meaning: "Sağlıklı", level: "A2" },
    { id: 1978, word: "Hear", meaning: "Duymak", level: "A2" },
    { id: 1979, word: "Hearing", meaning: "Duyma, Duruşma", level: "B2" },
    { id: 1980, word: "Heart", meaning: "Kalp", level: "A2" },
    { id: 1981, word: "Heat", meaning: "Isı", level: "A2" },
    { id: 1982, word: "Heating", meaning: "Isıtma", level: "B1" },
    { id: 1983, word: "Heaven", meaning: "Cennet", level: "B2" },
    { id: 1984, word: "Heavy", meaning: "Ağır", level: "A2" },
    { id: 1985, word: "Heel", meaning: "Topuk", level: "B2" },
    { id: 1986, word: "Height", meaning: "Yükseklik", level: "A2" },
    { id: 1987, word: "Helicopter", meaning: "Helikopter", level: "B1" },
    { id: 1988, word: "Hell", meaning: "Cehennem", level: "B2" },
    { id: 1989, word: "Hello", meaning: "Merhaba", level: "A2" },
    { id: 1990, word: "Help", meaning: "Yardım", level: "A2" },
    { id: 1991, word: "Helpful", meaning: "Yardımsever", level: "A2" },
    { id: 1992, word: "Her", meaning: "Onun (Kadın)", level: "A2" },
    { id: 1993, word: "Here", meaning: "Burada", level: "A2" },
    { id: 1994, word: "Hero", meaning: "Kahraman", level: "B1" },
    { id: 1995, word: "Hers", meaning: "Onunki (Kadın)", level: "A2" },
    { id: 1996, word: "Herself", meaning: "Kendisi (Kadın)", level: "A2" },
    { id: 1997, word: "Hesitate", meaning: "Tereddüt etmek", level: "B2" },
    { id: 1998, word: "Hi", meaning: "Selam", level: "A2" },
    { id: 1999, word: "Hide", meaning: "Saklamak", level: "A2" },
    { id: 2000, word: "High", meaning: "Yüksek", level: "A2" },
    { id: 2001, word: "Highlight", meaning: "Vurgulamak", level: "B2" },
    { id: 2002, word: "Highly", meaning: "Oldukça", level: "B1" },
    { id: 2003, word: "Highway", meaning: "Otoyol", level: "B1" },
    { id: 2004, word: "Hill", meaning: "Tepe", level: "A2" },
    { id: 2005, word: "Him", meaning: "Onu (Erkek)", level: "A2" },
    { id: 2006, word: "Himself", meaning: "Kendisi (Erkek)", level: "A2" },
    { id: 2007, word: "Hire", meaning: "Kiralamak, İşe almak", level: "B1" },
    { id: 2008, word: "His", meaning: "Onun (Erkek)", level: "A2" },
    { id: 2009, word: "Historical", meaning: "Tarihi", level: "B1" },
    { id: 2010, word: "History", meaning: "Tarih", level: "A2" },
    { id: 2011, word: "Hit", meaning: "Vurmak", level: "A2" },
    { id: 2012, word: "Hobby", meaning: "Hobi", level: "A2" },
    { id: 2013, word: "Hockey", meaning: "Hokey", level: "A2" },
    { id: 2014, word: "Hold", meaning: "Tutmak", level: "A2" },
    { id: 2015, word: "Hole", meaning: "Delik", level: "A2" },
    { id: 2016, word: "Holiday", meaning: "Tatil", level: "A2" },
    { id: 2017, word: "Hollow", meaning: "Oyuk", level: "B2" },
    { id: 2018, word: "Holy", meaning: "Kutsal", level: "B2" },
    { id: 2019, word: "Home", meaning: "Ev", level: "A2" },
    { id: 2020, word: "Homework", meaning: "Ödev", level: "A2" },
    { id: 2021, word: "Honest", meaning: "Dürüst", level: "B1" },
    { id: 2022, word: "Honor", meaning: "Onur", level: "B2" },
    { id: 2023, word: "Hook", meaning: "Kanca", level: "B2" },
    { id: 2024, word: "Hope", meaning: "Umut", level: "A2" },
    { id: 2025, word: "Horizontal", meaning: "Yatay", level: "B2" },
    { id: 2026, word: "Horrible", meaning: "Korkunç", level: "B1" },
    { id: 2027, word: "Horror", meaning: "Korku", level: "B1" },
    { id: 2028, word: "Horse", meaning: "At", level: "A2" },
    { id: 2029, word: "Hospital", meaning: "Hastane", level: "A2" },
    { id: 2030, word: "Host", meaning: "Ev sahibi", level: "B1" },
    { id: 2031, word: "Hot", meaning: "Sıcak", level: "A2" },
    { id: 2032, word: "Hotel", meaning: "Otel", level: "A2" },
    { id: 2033, word: "Hour", meaning: "Saat", level: "A2" },
    { id: 2034, word: "House", meaning: "Ev", level: "A2" },
    { id: 2035, word: "Household", meaning: "Ev halkı", level: "B2" },
    { id: 2036, word: "Housing", meaning: "Konut", level: "B2" },
    { id: 2037, word: "How", meaning: "Nasıl", level: "A2" },
    { id: 2038, word: "However", meaning: "Ancak", level: "A2" },
    { id: 2039, word: "Huge", meaning: "Devasa", level: "A2" },
    { id: 2040, word: "Human", meaning: "İnsan", level: "A2" },
    { id: 2041, word: "Humorous", meaning: "Mizahi", level: "B2" },
    { id: 2042, word: "Humour", meaning: "Mizah", level: "B2" },
    { id: 2043, word: "Hundred", meaning: "Yüz", level: "A2" },
    { id: 2044, word: "Hungry", meaning: "Aç", level: "A2" },
    { id: 2045, word: "Hunt", meaning: "Avlamak", level: "B1" },
    { id: 2046, word: "Hunting", meaning: "Avcılık", level: "B2" },
    { id: 2047, word: "Hurricane", meaning: "Kasırga", level: "B1" },
    { id: 2048, word: "Hurry", meaning: "Acele etmek", level: "B1" },
    { id: 2049, word: "Hurt", meaning: "İncitmek", level: "A2" },
    { id: 2050, word: "Husband", meaning: "Koca", level: "A2" },
    { id: 2051, word: "Hut", meaning: "Kulübe", level: "B2" },
    { id: 2052, word: "Ice", meaning: "Buz", level: "A2" },
    { id: 2053, word: "Idea", meaning: "Fikir", level: "A2" },
    { id: 2054, word: "Ideal", meaning: "İdeal", level: "A2" },
    { id: 2055, word: "Identify", meaning: "Tanımlamak", level: "A2" },
    { id: 2056, word: "Identity", meaning: "Kimlik", level: "B1" },
    { id: 2057, word: "If", meaning: "Eğer", level: "A2" },
    { id: 2058, word: "Ignore", meaning: "Görmezden gelmek", level: "B1" },
    { id: 2059, word: "Ill", meaning: "Hasta", level: "A2" },
    { id: 2060, word: "Illegal", meaning: "Yasadışı", level: "B1" },
    { id: 2061, word: "Illness", meaning: "Hastalık", level: "A2" },
    { id: 2062, word: "Illustrate", meaning: "Örneklemek, Resimlemek", level: "B2" },
    { id: 2063, word: "Illustration", meaning: "İllüstrasyon", level: "B2" },
    { id: 2064, word: "Image", meaning: "Görüntü", level: "A2" },
    { id: 2065, word: "Imaginary", meaning: "Hayali", level: "B1" },
    { id: 2066, word: "Imagination", meaning: "Hayal gücü", level: "B1" },
    { id: 2067, word: "Imagine", meaning: "Hayal etmek", level: "A2" },
    { id: 2068, word: "Immediate", meaning: "Acil", level: "B1" },
    { id: 2069, word: "Immediately", meaning: "Derhal", level: "A2" },
    { id: 2070, word: "Immigrant", meaning: "Göçmen", level: "B1" },
    { id: 2071, word: "Impact", meaning: "Etki", level: "B1" },
    { id: 2072, word: "Impatient", meaning: "Sabırsız", level: "B2" },
    { id: 2073, word: "Imply", meaning: "İma etmek", level: "B2" },
    { id: 2074, word: "Import", meaning: "İthalat", level: "B1" },
    { id: 2075, word: "Importance", meaning: "Önem", level: "B1" },
    { id: 2076, word: "Important", meaning: "Önemli", level: "A2" },
    { id: 2077, word: "Impose", meaning: "Dayatmak", level: "B2" },
    { id: 2078, word: "Impossible", meaning: "İmkansız", level: "A2" },
    { id: 2079, word: "Impress", meaning: "Etkilemek", level: "B2" },
    { id: 2080, word: "Impression", meaning: "İzlenim", level: "B1" },
    { id: 2081, word: "Impressive", meaning: "Etkileyici", level: "B1" },
    { id: 2082, word: "Improve", meaning: "Geliştirmek", level: "A2" },
    { id: 2083, word: "Improvement", meaning: "Gelişme", level: "B1" },
    { id: 2084, word: "In", meaning: "İçinde", level: "A2" },
    { id: 2085, word: "Incident", meaning: "Olay", level: "B2" },
    { id: 2086, word: "Include", meaning: "Dahil etmek", level: "A2" },
    { id: 2087, word: "Including", meaning: "Dahil", level: "A2" },
    { id: 2088, word: "Income", meaning: "Gelir", level: "B2" },
    { id: 2089, word: "Increase", meaning: "Artmak", level: "A2" },
    { id: 2090, word: "Increasingly", meaning: "Giderek artan şekilde", level: "B2" },
    { id: 2091, word: "Incredible", meaning: "İnanılmaz", level: "A2" },
    { id: 2092, word: "Incredibly", meaning: "İnanılmaz derecede", level: "B1" },
    { id: 2093, word: "Indeed", meaning: "Gerçekten", level: "B1" },
    { id: 2094, word: "Independent", meaning: "Bağımsız", level: "A2" },
    { id: 2095, word: "Indicate", meaning: "Belirtmek", level: "B1" },
    { id: 2096, word: "Indirect", meaning: "Dolaylı", level: "B1" },
    { id: 2097, word: "Individual", meaning: "Birey", level: "A2" },
    { id: 2098, word: "Indoor", meaning: "Kapalı mekan", level: "B1" },
    { id: 2099, word: "Indoors", meaning: "İçeri", level: "B1" },
    { id: 2100, word: "Industrial", meaning: "Endüstriyel", level: "B2" },
    { id: 2101, word: "Industry", meaning: "Endüstri", level: "A2" },
    { id: 2102, word: "Infection", meaning: "Enfeksiyon", level: "B2" },
    { id: 2103, word: "Influence", meaning: "Etki", level: "B1" },
    { id: 2104, word: "Inform", meaning: "Bilgilendirmek", level: "B2" },
    { id: 2105, word: "Information", meaning: "Bilgi", level: "A2" },
    { id: 2106, word: "Ingredient", meaning: "Malzeme", level: "B1" },
    { id: 2107, word: "Initial", meaning: "Başlangıç", level: "B2" },
    { id: 2108, word: "Initially", meaning: "Başlangıçta", level: "B2" },
    { id: 2109, word: "Initiative", meaning: "Girişim", level: "B2" },
    { id: 2110, word: "Injure", meaning: "Yaralamak", level: "B1" },
    { id: 2111, word: "Injured", meaning: "Yaralı", level: "B1" },
    { id: 2112, word: "Injury", meaning: "Yaralanma", level: "A2" },
    { id: 2113, word: "Ink", meaning: "Mürekkep", level: "B1" },
    { id: 2114, word: "Inner", meaning: "İç", level: "B2" },
    { id: 2115, word: "Innocent", meaning: "Masum", level: "B1" },
    { id: 2116, word: "Insect", meaning: "Böcek", level: "A2" },
    { id: 2117, word: "Insert", meaning: "Eklemek, Sokmak", level: "B2" },
    { id: 2118, word: "Inside", meaning: "İçeride", level: "A2" },
    { id: 2119, word: "Insight", meaning: "İçgörü", level: "B2" },
    { id: 2120, word: "Insist", meaning: "Israr etmek", level: "B2" },
    { id: 2121, word: "Inspire", meaning: "İlham vermek", level: "B2" },
    { id: 2122, word: "Install", meaning: "Kurmak", level: "B2" },
    { id: 2123, word: "Instance", meaning: "Örnek", level: "B2" },
    { id: 2124, word: "Instead", meaning: "Yerine", level: "A2" },
    { id: 2125, word: "Institute", meaning: "Enstitü", level: "B2" },
    { id: 2126, word: "Institution", meaning: "Kurum", level: "B2" },
    { id: 2127, word: "Instruction", meaning: "Talimat", level: "A2" },
    { id: 2128, word: "Instructor", meaning: "Eğitmen", level: "A2" },
    { id: 2129, word: "Instrument", meaning: "Enstrüman", level: "A2" },
    { id: 2130, word: "Insult", meaning: "Hakaret etmek", level: "B2" },
    { id: 2131, word: "Insurance", meaning: "Sigorta", level: "B2" },
    { id: 2132, word: "Intellectual", meaning: "Entelektüel", level: "B2" },
    { id: 2133, word: "Intelligence", meaning: "Zeka", level: "B1" },
    { id: 2134, word: "Intelligent", meaning: "Zeki", level: "A2" },
    { id: 2135, word: "Intend", meaning: "Niyet etmek", level: "B1" },
    { id: 2136, word: "Intense", meaning: "Yoğun", level: "B2" },
    { id: 2137, word: "Intention", meaning: "Niyet", level: "B1" },
    { id: 2138, word: "Interest", meaning: "İlgi", level: "A2" },
    { id: 2139, word: "Interested", meaning: "İlgili", level: "A2" },
    { id: 2140, word: "Interesting", meaning: "İlginç", level: "A2" },
    { id: 2141, word: "Internal", meaning: "Dahili", level: "B2" },
    { id: 2142, word: "International", meaning: "Uluslararası", level: "A2" },
    { id: 2143, word: "Internet", meaning: "İnternet", level: "A2" },
    { id: 2144, word: "Interpret", meaning: "Yorumlamak", level: "B2" },
    { id: 2145, word: "Interrupt", meaning: "Sözünü kesmek", level: "B1" },
    { id: 2146, word: "Interview", meaning: "Röportaj", level: "A2" },
    { id: 2147, word: "Into", meaning: "İçine", level: "A2" },
    { id: 2148, word: "Introduction", meaning: "Giriş", level: "A2" },
    { id: 2149, word: "Invent", meaning: "İcat etmek", level: "A2" },
    { id: 2150, word: "Invention", meaning: "İcat", level: "A2" },
    { id: 2151, word: "Invest", meaning: "Yatırım yapmak", level: "B1" },
    { id: 2152, word: "Investigate", meaning: "Araştırmak", level: "B1" },
    { id: 2153, word: "Investigation", meaning: "Soruşturma", level: "B2" },
    { id: 2154, word: "Investment", meaning: "Yatırım", level: "B2" },
    { id: 2155, word: "Invitation", meaning: "Davet", level: "A2" },
    { id: 2156, word: "Invite", meaning: "Davet etmek", level: "A2" },
    { id: 2157, word: "Involve", meaning: "İçermek", level: "A2" },
    { id: 2158, word: "Involved", meaning: "Dahil olmuş", level: "B1" },
    { id: 2159, word: "Iron", meaning: "Demir, Ütü", level: "B1" },
    { id: 2160, word: "Island", meaning: "Ada", level: "A2" },
    { id: 2161, word: "Issue", meaning: "Sorun", level: "B1" },
    { id: 2162, word: "It", meaning: "O (cansız)", level: "A2" },
    { id: 2163, word: "Item", meaning: "Öğe", level: "A2" },
    { id: 2164, word: "Its", meaning: "Onun (cansız)", level: "A2" },
    { id: 2165, word: "Itself", meaning: "Kendisi (cansız)", level: "A2" },
    { id: 2166, word: "Jacket", meaning: "Ceket", level: "A2" },
    { id: 2167, word: "Jam", meaning: "Reçel, Sıkışıklık", level: "A2" },
    { id: 2168, word: "January", meaning: "Ocak", level: "A2" },
    { id: 2169, word: "Jealous", meaning: "Kıskanç", level: "B1" },
    { id: 2170, word: "Jeans", meaning: "Kot pantolon", level: "A2" },
    { id: 2171, word: "Jelly", meaning: "Jöle", level: "B1" },
    { id: 2172, word: "Jewellery", meaning: "Mücevher", level: "A2" },
    { id: 2173, word: "Job", meaning: "İş", level: "A2" },
    { id: 2174, word: "Join", meaning: "Katılmak", level: "A2" },
    { id: 2175, word: "Joke", meaning: "Şaka", level: "A2" },
    { id: 2176, word: "Journalist", meaning: "Gazeteci", level: "A2" },
    { id: 2177, word: "Journey", meaning: "Yolculuk", level: "A2" },
    { id: 2178, word: "Joy", meaning: "Neşe", level: "B2" },
    { id: 2179, word: "Judge", meaning: "Yargıç", level: "B1" },
    { id: 2180, word: "Judgment", meaning: "Yargı", level: "B2" },
    { id: 2181, word: "Juice", meaning: "Meyve suyu", level: "A2" },
    { id: 2182, word: "July", meaning: "Temmuz", level: "A2" },
    { id: 2183, word: "Jump", meaning: "Zıplamak", level: "A2" },
    { id: 2184, word: "June", meaning: "Haziran", level: "A2" },
    { id: 2185, word: "Junior", meaning: "Kıdemsiz", level: "B2" },
    { id: 2186, word: "Just", meaning: "Sadece", level: "A2" },
    { id: 2187, word: "Justice", meaning: "Adalet", level: "B2" },
    { id: 2188, word: "Justify", meaning: "Haklı çıkarmak", level: "B2" },
    { id: 2189, word: "Keep", meaning: "Tutmak, Saklamak", level: "A2" },
    { id: 2190, word: "Key", meaning: "Anahtar", level: "A2" },
    { id: 2191, word: "Keyboard", meaning: "Klavye", level: "A2" },
    { id: 2192, word: "Kick", meaning: "Tekmelemek", level: "A2" },
    { id: 2193, word: "Kid", meaning: "Çocuk", level: "A2" },
    { id: 2194, word: "Kill", meaning: "Öldürmek", level: "A2" },
    { id: 2195, word: "Killing", meaning: "Öldürme", level: "B1" },
    { id: 2196, word: "Kilometer", meaning: "Kilometre", level: "A2" },
    { id: 2197, word: "Kind", meaning: "Tür, Nazik", level: "A2" },
    { id: 2198, word: "King", meaning: "Kral", level: "A2" },
    { id: 2199, word: "Kiss", meaning: "Öpmek", level: "A2" },
    { id: 2200, word: "Kitchen", meaning: "Mutfak", level: "A2" }
];
