[
    { id: 1601, word: "Efficiency", meaning: "Verimlilik", level: "B2" },
    { id: 1602, word: "Efficient", meaning: "Verimli", level: "B2" },
    { id: 1603, word: "Effort", meaning: "Çaba", level: "A2" },
    { id: 1604, word: "Egg", meaning: "Yumurta", level: "A2" },
    { id: 1605, word: "Eight", meaning: "Sekiz", level: "A2" },
    { id: 1606, word: "Eighteen", meaning: "On sekiz", level: "A2" },
    { id: 1607, word: "Eighty", meaning: "Seksen", level: "A2" },
    { id: 1608, word: "Either", meaning: "Ya ... ya da", level: "A2" },
    { id: 1609, word: "Elderly", meaning: "Yaşlı", level: "B2" },
    { id: 1610, word: "Elect", meaning: "Seçmek (oyla)", level: "B2" },
    { id: 1611, word: "Election", meaning: "Seçim", level: "B1" },
    { id: 1612, word: "Electric", meaning: "Elektrikli", level: "A2" },
    { id: 1613, word: "Electrical", meaning: "Elektriksel", level: "A2" },
    { id: 1614, word: "Electricity", meaning: "Elektrik", level: "A2" },
    { id: 1615, word: "Electronic", meaning: "Elektronik", level: "A2" },
    { id: 1616, word: "Element", meaning: "Element, Unsur", level: "B1" },
    { id: 1617, word: "Elephant", meaning: "Fil", level: "A2" },
    { id: 1618, word: "Elevator", meaning: "Asansör", level: "A2" },
    { id: 1619, word: "Eleven", meaning: "On bir", level: "A2" },
    { id: 1620, word: "Else", meaning: "Başka", level: "A2" },
    { id: 1621, word: "Elsewhere", meaning: "Başka yerde", level: "B2" },
    { id: 1622, word: "Email", meaning: "E-posta", level: "A2" },
    { id: 1623, word: "Embarrassed", meaning: "Utanmış", level: "B1" },
    { id: 1624, word: "Emerge", meaning: "Ortaya çıkmak", level: "B2" },
    { id: 1625, word: "Emergency", meaning: "Acil durum", level: "B1" },
    { id: 1626, word: "Emotion", meaning: "Duygu", level: "B1" },
    { id: 1627, word: "Emotional", meaning: "Duygusal", level: "B2" },
    { id: 1628, word: "Emphasis", meaning: "Vurgu", level: "B2" },
    { id: 1629, word: "Emphasize", meaning: "Vurgulamak", level: "B2" },
    { id: 1630, word: "Employ", meaning: "İşe almak", level: "A2" },
    { id: 1631, word: "Employee", meaning: "Çalışan", level: "A2" },
    { id: 1632, word: "Employer", meaning: "İşveren", level: "A2" },
    { id: 1633, word: "Employment", meaning: "İstihdam", level: "B1" },
    { id: 1634, word: "Empty", meaning: "Boş", level: "A2" },
    { id: 1635, word: "Enable", meaning: "Olanak sağlamak", level: "B2" },
    { id: 1636, word: "Encounter", meaning: "Karşılaşmak", level: "B2" },
    { id: 1637, word: "Encourage", meaning: "Cesaretlendirmek", level: "B1" },
    { id: 1638, word: "End", meaning: "Son, Bitirmek", level: "A2" },
    { id: 1639, word: "Ending", meaning: "Bitiş", level: "A2" },
    { id: 1640, word: "Enemy", meaning: "Düşman", level: "B1" },
    { id: 1641, word: "Energy", meaning: "Enerji", level: "A2" },
    { id: 1642, word: "Engage", meaning: "İlgi çekmek, Nişanlanmak", level: "B2" },
    { id: 1643, word: "Engine", meaning: "Motor", level: "A2" },
    { id: 1644, word: "Engineer", meaning: "Mühendis", level: "A2" },
    { id: 1645, word: "Engineering", meaning: "Mühendislik", level: "B1" },
    { id: 1646, word: "Enhance", meaning: "Geliştirmek", level: "B2" },
    { id: 1647, word: "Enjoy", meaning: "Zevk almak", level: "A2" },
    { id: 1648, word: "Enormous", meaning: "Kocaman", level: "A2" },
    { id: 1649, word: "Enough", meaning: "Yeterli", level: "A2" },
    { id: 1650, word: "Enquiry", meaning: "Soruşturma", level: "B2" },
    { id: 1651, word: "Ensure", meaning: "Garantiye almak", level: "B2" },
    { id: 1652, word: "Enter", meaning: "Girmek", level: "A2" },
    { id: 1653, word: "Entertain", meaning: "Eğlendirmek", level: "B1" },
    { id: 1654, word: "Entertainment", meaning: "Eğlence", level: "B1" },
    { id: 1655, word: "Enthusiasm", meaning: "Heves", level: "B2" },
    { id: 1656, word: "Enthusiastic", meaning: "Hevesli", level: "B2" },
    { id: 1657, word: "Entire", meaning: "Tüm", level: "B2" },
    { id: 1658, word: "Entrance", meaning: "Giriş", level: "B1" },
    { id: 1659, word: "Entry", meaning: "Giriş", level: "B1" },
    { id: 1660, word: "Environment", meaning: "Çevre", level: "A2" },
    { id: 1661, word: "Environmental", meaning: "Çevresel", level: "B1" },
    { id: 1662, word: "Episode", meaning: "Bölüm", level: "B1" },
    { id: 1663, word: "Equal", meaning: "Eşit", level: "B1" },
    { id: 1664, word: "Equipment", meaning: "Ekipman", level: "A2" },
    { id: 1665, word: "Error", meaning: "Hata", level: "A2" },
    { id: 1666, word: "Escape", meaning: "Kaçmak", level: "B1" },
    { id: 1667, word: "Especially", meaning: "Özellikle", level: "A2" },
    { id: 1668, word: "Essay", meaning: "Deneme (yazı)", level: "A2" },
    { id: 1669, word: "Essential", meaning: "Temel, Gerekli", level: "B1" },
    { id: 1670, word: "Establish", meaning: "Kurmak", level: "B2" },
    { id: 1671, word: "Estate", meaning: "Mülk", level: "B2" },
    { id: 1672, word: "Estimate", meaning: "Tahmin etmek", level: "B2" },
    { id: 1673, word: "Ethical", meaning: "Etik", level: "B2" },
    { id: 1674, word: "Euro", meaning: "Avro", level: "A2" },
    { id: 1675, word: "Evaluate", meaning: "Değerlendirmek", level: "B2" },
    { id: 1676, word: "Even", meaning: "Hatta", level: "A2" },
    { id: 1677, word: "Evening", meaning: "Akşam", level: "A2" },
    { id: 1678, word: "Event", meaning: "Olay", level: "A2" },
    { id: 1679, word: "Eventually", meaning: "Sonunda", level: "B1" },
    { id: 1680, word: "Ever", meaning: "Hiç", level: "A2" },
    { id: 1681, word: "Every", meaning: "Her", level: "A2" },
    { id: 1682, word: "Everybody", meaning: "Herkes", level: "A2" },
    { id: 1683, word: "Everyday", meaning: "Gündelik", level: "A2" },
    { id: 1684, word: "Everyone", meaning: "Herkes", level: "A2" },
    { id: 1685, word: "Everything", meaning: "Her şey", level: "A2" },
    { id: 1686, word: "Everywhere", meaning: "Her yer", level: "A2" },
    { id: 1687, word: "Evidence", meaning: "Kanıt", level: "A2" },
    { id: 1688, word: "Evil", meaning: "Kötü", level: "B2" },
    { id: 1689, word: "Exact", meaning: "Tam, Kesin", level: "A2" },
    { id: 1690, word: "Exactly", meaning: "Kesinlikle", level: "A2" },
    { id: 1691, word: "Exam", meaning: "Sınav", level: "A2" },
    { id: 1692, word: "Examination", meaning: "İnceleme, Sınav", level: "B2" },
    { id: 1693, word: "Examine", meaning: "İncelemek", level: "B1" },
    { id: 1694, word: "Example", meaning: "Örnek", level: "A2" },
    { id: 1695, word: "Excellent", meaning: "Mükemmel", level: "A2" },
    { id: 1696, word: "Except", meaning: "Hariç", level: "A2" },
    { id: 1697, word: "Exchange", meaning: "Değiş tokuş", level: "B1" },
    { id: 1698, word: "Excited", meaning: "Heyecanlı", level: "A2" },
    { id: 1699, word: "Excitement", meaning: "Heyecan", level: "B1" },
    { id: 1700, word: "Exciting", meaning: "Heyecan verici", level: "A2" },
    { id: 1701, word: "Excuse", meaning: "Mazeret", level: "B1" },
    { id: 1702, word: "Executive", meaning: "Yönetici", level: "B2" },
    { id: 1703, word: "Exercise", meaning: "Egzersiz", level: "A2" },
    { id: 1704, word: "Exhibition", meaning: "Sergi", level: "B1" },
    { id: 1705, word: "Exist", meaning: "Var olmak", level: "A2" },
    { id: 1706, word: "Existence", meaning: "Varlık", level: "B2" },
    { id: 1707, word: "Expand", meaning: "Genişlemek", level: "B1" },
    { id: 1708, word: "Expect", meaning: "Beklemek (ummak)", level: "A2" },
    { id: 1709, word: "Expectation", meaning: "Beklenti", level: "B2" },
    { id: 1710, word: "Expense", meaning: "Masraf", level: "B2" },
    { id: 1711, word: "Expensive", meaning: "Pahalı", level: "A2" },
    { id: 1712, word: "Experience", meaning: "Deneyim", level: "A2" },
    { id: 1713, word: "Experienced", meaning: "Deneyimli", level: "B1" },
    { id: 1714, word: "Experiment", meaning: "Deney", level: "A2" },
    { id: 1715, word: "Expert", meaning: "Uzman", level: "A2" },
    { id: 1716, word: "Explain", meaning: "Açıklamak", level: "A2" },
    { id: 1717, word: "Explanation", meaning: "Açıklama", level: "A2" },
    { id: 1718, word: "Explode", meaning: "Patlamak", level: "B1" },
    { id: 1719, word: "Explore", meaning: "Keşfetmek", level: "B1" },
    { id: 1720, word: "Explosion", meaning: "Patlama", level: "B1" },
    { id: 1721, word: "Export", meaning: "İhracat", level: "B1" },
    { id: 1722, word: "Expose", meaning: "Maruz bırakmak", level: "B2" },
    { id: 1723, word: "Express", meaning: "İfade etmek", level: "A2" },
    { id: 1724, word: "Expression", meaning: "İfade", level: "A2" },
    { id: 1725, word: "Extend", meaning: "Uzatmak", level: "B2" },
    { id: 1726, word: "Extension", meaning: "Uzantı", level: "B2" },
    { id: 1727, word: "Extensive", meaning: "Kapsamlı", level: "B2" },
    { id: 1728, word: "Extent", meaning: "Boyut, Derece", level: "B2" },
    { id: 1729, word: "External", meaning: "Harici", level: "B2" },
    { id: 1730, word: "Extra", meaning: "Ekstra", level: "A2" },
    { id: 1731, word: "Extraordinary", meaning: "Olağanüstü", level: "B2" },
    { id: 1732, word: "Extreme", meaning: "Aşırı", level: "A2" },
    { id: 1733, word: "Extremely", meaning: "Son derece", level: "A2" },
    { id: 1734, word: "Eye", meaning: "Göz", level: "A2" },
    { id: 1735, word: "Face", meaning: "Yüz", level: "A2" },
    { id: 1736, word: "Facility", meaning: "Tesis", level: "B2" },
    { id: 1737, word: "Fact", meaning: "Gerçek", level: "A2" },
    { id: 1738, word: "Factor", meaning: "Faktör", level: "A2" },
    { id: 1739, word: "Factory", meaning: "Fabrika", level: "A2" },
    { id: 1740, word: "Fail", meaning: "Başarısız olmak", level: "A2" },
    { id: 1741, word: "Failure", meaning: "Başarısızlık", level: "B2" },
    { id: 1742, word: "Fair", meaning: "Adil", level: "A2" },
    { id: 1743, word: "Fairly", meaning: "Oldukça", level: "B1" },
    { id: 1744, word: "Faith", meaning: "İnanç", level: "B2" },
    { id: 1745, word: "Fall", meaning: "Düşmek", level: "A2" },
    { id: 1746, word: "False", meaning: "Yanlış", level: "A2" },
    { id: 1747, word: "Familiar", meaning: "Tanıdık", level: "B1" },
    { id: 1748, word: "Family", meaning: "Aile", level: "A2" },
    { id: 1749, word: "Famous", meaning: "Ünlü", level: "A2" },
    { id: 1750, word: "Fan", meaning: "Hayran, Vantilatör", level: "A2" },
    { id: 1751, word: "Fancy", meaning: "Süslü", level: "B1" },
    { id: 1752, word: "Far", meaning: "Uzak", level: "A2" },
    { id: 1753, word: "Farm", meaning: "Çiftlik", level: "A2" },
    { id: 1754, word: "Farmer", meaning: "Çiftçi", level: "A2" },
    { id: 1755, word: "Farming", meaning: "Çiftçilik", level: "A2" },
    { id: 1756, word: "Fascinating", meaning: "Büyüleyici", level: "B2" },
    { id: 1757, word: "Fashion", meaning: "Moda", level: "A2" },
    { id: 1758, word: "Fast", meaning: "Hızlı", level: "A2" },
    { id: 1759, word: "Fat", meaning: "Şişman", level: "A2" },
    { id: 1760, word: "Father", meaning: "Baba", level: "A2" },
    { id: 1761, word: "Fault", meaning: "Hata", level: "B2" },
    { id: 1762, word: "Favor", meaning: "İyilik", level: "B2" },
    { id: 1763, word: "Favorite", meaning: "Favori", level: "A2" },
    { id: 1764, word: "Fear", meaning: "Korku", level: "A2" },
    { id: 1765, word: "Feather", meaning: "Tüy", level: "B2" },
    { id: 1766, word: "Feature", meaning: "Özellik", level: "A2" },
    { id: 1767, word: "February", meaning: "Şubat", level: "A2" },
    { id: 1768, word: "Fee", meaning: "Ücret", level: "B2" },
    { id: 1769, word: "Feed", meaning: "Beslemek", level: "A2" },
    { id: 1770, word: "Feedback", meaning: "Geri bildirim", level: "B2" },
    { id: 1771, word: "Feel", meaning: "Hissetmek", level: "A2" },
    { id: 1772, word: "Feeling", meaning: "His", level: "A2" },
    { id: 1773, word: "Fellow", meaning: "Dost", level: "B2" },
    { id: 1774, word: "Female", meaning: "Dişi", level: "A2" },
    { id: 1775, word: "Fence", meaning: "Çit", level: "B1" },
    { id: 1776, word: "Festival", meaning: "Festival", level: "A2" },
    { id: 1777, word: "Few", meaning: "Az", level: "A2" },
    { id: 1778, word: "Fiction", meaning: "Kurgu", level: "A2" },
    { id: 1779, word: "Field", meaning: "Alan, Tarla", level: "A2" },
    { id: 1780, word: "Fifteen", meaning: "On beş", level: "A2" },
    { id: 1781, word: "Fifth", meaning: "Beşinci", level: "A2" },
    { id: 1782, word: "Fifty", meaning: "Elli", level: "A2" },
    { id: 1783, word: "Fight", meaning: "Dövüşmek", level: "A2" },
    { id: 1784, word: "Fighting", meaning: "Dövüş", level: "A2" },
    { id: 1785, word: "Figure", meaning: "Rakam, Şekil", level: "A2" },
    { id: 1786, word: "File", meaning: "Dosya", level: "A2" },
    { id: 1787, word: "Fill", meaning: "Doldurmak", level: "A2" },
    { id: 1788, word: "Film", meaning: "Film", level: "A2" },
    { id: 1789, word: "Final", meaning: "Son", level: "A2" },
    { id: 1790, word: "Finally", meaning: "Sonunda", level: "A2" },
    { id: 1791, word: "Finance", meaning: "Finans", level: "B2" },
    { id: 1792, word: "Financial", meaning: "Finansal", level: "B1" },
    { id: 1793, word: "Find", meaning: "Bulmak", level: "A2" },
    { id: 1794, word: "Finding", meaning: "Bulgu", level: "B2" },
    { id: 1795, word: "Fine", meaning: "İyi, İnce", level: "A2" },
    { id: 1796, word: "Finger", meaning: "Parmak", level: "A2" },
    { id: 1797, word: "Finish", meaning: "Bitirmek", level: "A2" },
    { id: 1798, word: "Fire", meaning: "Ateş", level: "A2" },
    { id: 1799, word: "Firm", meaning: "Firma", level: "B2" },
    { id: 1800, word: "First", meaning: "Birinci", level: "A2" },
    { id: 1801, word: "Fish", meaning: "Balık", level: "A2" },
    { id: 1802, word: "Fishing", meaning: "Balıkçılık", level: "A2" },
    { id: 1803, word: "Fit", meaning: "Uymak, Fit", level: "A2" },
    { id: 1804, word: "Fitness", meaning: "Zindelik", level: "B1" },
    { id: 1805, word: "Five", meaning: "Beş", level: "A2" },
    { id: 1806, word: "Fix", meaning: "Düzeltmek", level: "A2" },
    { id: 1807, word: "Fixed", meaning: "Sabit", level: "B1" },
    { id: 1808, word: "Flag", meaning: "Bayrak", level: "B1" },
    { id: 1809, word: "Flame", meaning: "Alev", level: "B2" },
    { id: 1810, word: "Flash", meaning: "Flaş", level: "B2" },
    { id: 1811, word: "Flat", meaning: "Düz, Daire", level: "A2" },
    { id: 1812, word: "Flexible", meaning: "Esnek", level: "B2" },
    { id: 1813, word: "Flight", meaning: "Uçuş", level: "A2" },
    { id: 1814, word: "Float", meaning: "Yüzmek (su üstünde)", level: "B2" },
    { id: 1815, word: "Flood", meaning: "Sel", level: "B1" },
    { id: 1816, word: "Floor", meaning: "Zemin", level: "A2" },
    { id: 1817, word: "Flour", meaning: "Un", level: "B1" },
    { id: 1818, word: "Flow", meaning: "Akış", level: "B1" },
    { id: 1819, word: "Flower", meaning: "Çiçek", level: "A2" },
    { id: 1820, word: "Flu", meaning: "Grip", level: "A2" },
    { id: 1821, word: "Fly", meaning: "Uçmak", level: "A2" },
    { id: 1822, word: "Flying", meaning: "Uçan", level: "A2" },
    { id: 1823, word: "Focus", meaning: "Odak", level: "A2" },
    { id: 1824, word: "Fold", meaning: "Katlamak", level: "B1" },
    { id: 1825, word: "Folding", meaning: "Katlanır", level: "B2" },
    { id: 1826, word: "Follow", meaning: "Takip etmek", level: "A2" },
    { id: 1827, word: "Following", meaning: "Takip eden", level: "A2" },
    { id: 1828, word: "Food", meaning: "Yiyecek", level: "A2" },
    { id: 1829, word: "Foot", meaning: "Ayak", level: "A2" },
    { id: 1830, word: "Football", meaning: "Futbol", level: "A2" },
    { id: 1831, word: "For", meaning: "İçin", level: "A2" },
    { id: 1832, word: "Force", meaning: "Güç", level: "B1" },
    { id: 1833, word: "Foreign", meaning: "Yabancı", level: "A2" },
    { id: 1834, word: "Forest", meaning: "Orman", level: "A2" },
    { id: 1835, word: "Forever", meaning: "Sonsuza dek", level: "B1" },
    { id: 1836, word: "Forget", meaning: "Unutmak", level: "A2" },
    { id: 1837, word: "Forgive", meaning: "Affetmek", level: "B2" },
    { id: 1838, word: "Fork", meaning: "Çatal", level: "A2" },
    { id: 1839, word: "Form", meaning: "Form", level: "A2" },
    { id: 1840, word: "Formal", meaning: "Resmi", level: "A2" },
    { id: 1841, word: "Former", meaning: "Eski, Önceki", level: "B2" },
    { id: 1842, word: "Fortunately", meaning: "Neyse ki", level: "A2" },
    { id: 1843, word: "Fortune", meaning: "Servet, Şans", level: "B2" },
    { id: 1844, word: "Forty", meaning: "Kırk", level: "A2" },
    { id: 1845, word: "Forward", meaning: "İleri", level: "A2" },
    { id: 1846, word: "Found", meaning: "Kurmak", level: "B2" },
    { id: 1847, word: "Four", meaning: "Dört", level: "A2" },
    { id: 1848, word: "Fourteen", meaning: "On dört", level: "A2" },
    { id: 1849, word: "Fourth", meaning: "Dördüncü", level: "A2" },
    { id: 1850, word: "Frame", meaning: "Çerçeve", level: "B1" },
    { id: 1851, word: "Free", meaning: "Özgür, Bedava", level: "A2" },
    { id: 1852, word: "Freedom", meaning: "Özgürlük", level: "B2" },
    { id: 1853, word: "Freeze", meaning: "Donmak", level: "B1" },
    { id: 1854, word: "Frequency", meaning: "Sıklık", level: "B2" },
    { id: 1855, word: "Frequently", meaning: "Sık sık", level: "B2" },
    { id: 1856, word: "Fresh", meaning: "Taze", level: "A2" },
    { id: 1857, word: "Friday", meaning: "Cuma", level: "A2" },
    { id: 1858, word: "Fridge", meaning: "Buzdolabı", level: "A2" },
    { id: 1859, word: "Friend", meaning: "Arkadaş", level: "A2" },
    { id: 1860, word: "Friendly", meaning: "Arkadaş canlısı", level: "A2" },
    { id: 1861, word: "Friendship", meaning: "Arkadaşlık", level: "B1" },
    { id: 1862, word: "Frighten", meaning: "Korkutmak", level: "B1" },
    { id: 1863, word: "Frightened", meaning: "Korkmuş", level: "B1" },
    { id: 1864, word: "Frightening", meaning: "Korkutucu", level: "B1" },
    { id: 1865, word: "Frog", meaning: "Kurbağa", level: "A2" },
    { id: 1866, word: "From", meaning: "-den, -dan", level: "A2" },
    { id: 1867, word: "Front", meaning: "Ön", level: "A2" },
    { id: 1868, word: "Frozen", meaning: "Donmuş", level: "B1" },
    { id: 1869, word: "Fruit", meaning: "Meyve", level: "A2" },
    { id: 1870, word: "Fry", meaning: "Kızartmak", level: "B1" },
    { id: 1871, word: "Fuel", meaning: "Yakıt", level: "B1" },
    { id: 1872, word: "Full", meaning: "Dolu", level: "A2" },
    { id: 1873, word: "Fully", meaning: "Tamamen", level: "B2" },
    { id: 1874, word: "Fun", meaning: "Eğlence", level: "A2" },
    { id: 1875, word: "Function", meaning: "Fonksiyon", level: "B1" },
    { id: 1876, word: "Fund", meaning: "Fon", level: "B2" },
    { id: 1877, word: "Fundamental", meaning: "Temel", level: "B2" },
    { id: 1878, word: "Funding", meaning: "Fonlama", level: "B2" },
    { id: 1879, word: "Funny", meaning: "Komik", level: "A2" },
    { id: 1880, word: "Fur", meaning: "Kürk", level: "B1" },
    { id: 1881, word: "Furniture", meaning: "Mobilya", level: "A2" },
    { id: 1882, word: "Further", meaning: "Daha ileri", level: "A2" },
    { id: 1883, word: "Future", meaning: "Gelecek", level: "A2" },
    { id: 1884, word: "Gain", meaning: "Kazanmak", level: "B2" },
    { id: 1885, word: "Gallery", meaning: "Galeri", level: "A2" },
    { id: 1886, word: "Game", meaning: "Oyun", level: "A2" },
    { id: 1887, word: "Gang", meaning: "Çete", level: "B2" },
    { id: 1888, word: "Gap", meaning: "Boşluk", level: "A2" },
    { id: 1889, word: "Garage", meaning: "Garaj", level: "A2" },
    { id: 1890, word: "Garden", meaning: "Bahçe", level: "A2" },
    { id: 1891, word: "Gas", meaning: "Gaz", level: "A2" },
    { id: 1892, word: "Gate", meaning: "Kapı (Büyük)", level: "A2" },
    { id: 1893, word: "Gather", meaning: "Toplamak", level: "B2" },
    { id: 1894, word: "General", meaning: "Genel", level: "A2" },
    { id: 1895, word: "Generally", meaning: "Genellikle", level: "B1" },
    { id: 1896, word: "Generate", meaning: "Üretmek", level: "B2" },
    { id: 1897, word: "Generation", meaning: "Nesil", level: "B1" },
    { id: 1898, word: "Generous", meaning: "Cömert", level: "B1" },
    { id: 1899, word: "Genre", meaning: "Tür", level: "B2" },
    { id: 1900, word: "Gentle", meaning: "Nazik", level: "B1" }
];
