[
    { id: 2201, word: "Kitten", meaning: "Kedi yavrusu", level: "A2" },
    { id: 2202, word: "Knee", meaning: "Diz", level: "A2" },
    { id: 2203, word: "Knife", meaning: "Bıçak", level: "A2" },
    { id: 2204, word: "Knock", meaning: "Kapı çalmak", level: "A2" },
    { id: 2205, word: "Know", meaning: "Bilmek", level: "A2" },
    { id: 2206, word: "Knowledge", meaning: "Bilgi", level: "B1" },
    { id: 2207, word: "Label", meaning: "Etiket", level: "A2" },
    { id: 2208, word: "Laboratory", meaning: "Laboratuvar", level: "B1" },
    { id: 2209, word: "Labour", meaning: "Emek, İş gücü", level: "B2" },
    { id: 2210, word: "Lack", meaning: "Eksiklik", level: "B1" },
    { id: 2211, word: "Lady", meaning: "Bayan", level: "A2" },
    { id: 2212, word: "Lake", meaning: "Göl", level: "A2" },
    { id: 2213, word: "Lamp", meaning: "Lamba", level: "A2" },
    { id: 2214, word: "Land", meaning: "Kara, Arsa", level: "A2" },
    { id: 2215, word: "Landscape", meaning: "Manzara", level: "B1" },
    { id: 2216, word: "Lane", meaning: "Şerit, Yol", level: "B1" },
    { id: 2217, word: "Language", meaning: "Dil", level: "A2" },
    { id: 2218, word: "Laptop", meaning: "Dizüstü bilgisayar", level: "A2" },
    { id: 2219, word: "Large", meaning: "Geniş, Büyük", level: "A2" },
    { id: 2220, word: "Largely", meaning: "Büyük oranda", level: "B2" },
    { id: 2221, word: "Last", meaning: "Son, Geçen", level: "A2" },
    { id: 2222, word: "Late", meaning: "Geç", level: "A2" },
    { id: 2223, word: "Later", meaning: "Daha sonra", level: "A2" },
    { id: 2224, word: "Latest", meaning: "En yeni", level: "B1" },
    { id: 2225, word: "Laugh", meaning: "Gülmek", level: "A2" },
    { id: 2226, word: "Launch", meaning: "Başlatmak, Fırlatmak", level: "B1" },
    { id: 2227, word: "Law", meaning: "Hukuk, Yasa", level: "A2" },
    { id: 2228, word: "Lawyer", meaning: "Avukat", level: "A2" },
    { id: 2229, word: "Lay", meaning: "Yatırmak, Koymak", level: "B1" },
    { id: 2230, word: "Layer", meaning: "Tabaka", level: "B1" },
    { id: 2231, word: "Lazy", meaning: "Tembel", level: "A2" },
    { id: 2232, word: "Lead", meaning: "Liderlik etmek, Yol göstermek", level: "A2" },
    { id: 2233, word: "Leader", meaning: "Lider", level: "A2" },
    { id: 2234, word: "Leadership", meaning: "Liderlik", level: "B1" },
    { id: 2235, word: "Leading", meaning: "Önde gelen", level: "B1" },
    { id: 2236, word: "Leaf", meaning: "Yaprak", level: "A2" },
    { id: 2237, word: "League", meaning: "Lig", level: "B1" },
    { id: 2238, word: "Lean", meaning: "Eğilmek, Yaslanmak", level: "B2" },
    { id: 2239, word: "Learn", meaning: "Öğrenmek", level: "A2" },
    { id: 2240, word: "Learning", meaning: "Öğrenme", level: "A2" },
    { id: 2241, word: "Least", meaning: "En az", level: "A2" },
    { id: 2242, word: "Leather", meaning: "Deri", level: "B1" },
    { id: 2243, word: "Leave", meaning: "Ayrılmak", level: "A2" },
    { id: 2244, word: "Lecture", meaning: "Ders, Konferans", level: "B1" },
    { id: 2245, word: "Left", meaning: "Sol", level: "A2" },
    { id: 2246, word: "Leg", meaning: "Bacak", level: "A2" },
    { id: 2247, word: "Legal", meaning: "Yasal", level: "B1" },
    { id: 2248, word: "Legend", meaning: "Efsane", level: "B1" },
    { id: 2249, word: "Leisure", meaning: "Boş vakit", level: "B2" },
    { id: 2250, word: "Lemon", meaning: "Limon", level: "A2" },
    { id: 2251, word: "Lend", meaning: "Ödünç vermek", level: "A2" },
    { id: 2252, word: "Length", meaning: "Uzunluk", level: "B1" },
    { id: 2253, word: "Less", meaning: "Daha az", level: "A2" },
    { id: 2254, word: "Lesson", meaning: "Ders", level: "A2" },
    { id: 2255, word: "Let", meaning: "İzin vermek", level: "A2" },
    { id: 2256, word: "Letter", meaning: "Mektup, Harf", level: "A2" },
    { id: 2257, word: "Level", meaning: "Seviye", level: "A2" },
    { id: 2258, word: "Liberal", meaning: "Liberal", level: "B2" },
    { id: 2259, word: "Library", meaning: "Kütüphane", level: "A2" },
    { id: 2260, word: "License", meaning: "Lisans", level: "B1" },
    { id: 2261, word: "Lie", meaning: "Yalan söylemek, Uzanmak", level: "A2" },
    { id: 2262, word: "Life", meaning: "Yaşam", level: "A2" },
    { id: 2263, word: "Lifestyle", meaning: "Yaşam tarzı", level: "B1" },
    { id: 2264, word: "Lift", meaning: "Asansör, Kaldırmak", level: "A2" },
    { id: 2265, word: "Light", meaning: "Işık, Hafif", level: "A2" },
    { id: 2266, word: "Like", meaning: "Sevmek, Gibi", level: "A2" },
    { id: 2267, word: "Likely", meaning: "Muhtemelen", level: "B1" },
    { id: 2268, word: "Limit", meaning: "Limit", level: "B1" },
    { id: 2269, word: "Limited", meaning: "Kısıtlı", level: "B2" },
    { id: 2270, word: "Line", meaning: "Çizgi, Hat", level: "A2" },
    { id: 2271, word: "Link", meaning: "Bağlantı", level: "B1" },
    { id: 2272, word: "Lion", meaning: "Aslan", level: "A2" },
    { id: 2273, word: "Lip", meaning: "Dudak", level: "A2" },
    { id: 2274, word: "Liquid", meaning: "Sıvı", level: "B1" },
    { id: 2275, word: "List", meaning: "Liste", level: "A2" },
    { id: 2276, word: "Listen", meaning: "Dinlemek", level: "A2" },
    { id: 2277, word: "Listener", meaning: "Dinleyici", level: "A2" },
    { id: 2278, word: "Literature", meaning: "Edebiyat", level: "B1" },
    { id: 2279, word: "Little", meaning: "Küçük, Az", level: "A2" },
    { id: 2280, word: "Live", meaning: "Yaşamak", level: "A2" },
    { id: 2281, word: "Living", meaning: "Yaşayan", level: "A2" },
    { id: 2282, word: "Load", meaning: "Yük", level: "B1" },
    { id: 2283, word: "Loan", meaning: "Kredi, Borç", level: "B2" },
    { id: 2284, word: "Local", meaning: "Yerel", level: "A2" },
    { id: 2285, word: "Locate", meaning: "Yerleştirmek, Bulmak", level: "B2" },
    { id: 2286, word: "Location", meaning: "Konum", level: "A2" },
    { id: 2287, word: "Lock", meaning: "Kilitlemek", level: "A2" },
    { id: 2288, word: "Logic", meaning: "Mantık", level: "B1" },
    { id: 2289, word: "Logical", meaning: "Mantıklı", level: "B1" },
    { id: 2290, word: "Lonely", meaning: "Yalnız (hissetmek)", level: "B1" },
    { id: 2291, word: "Long", meaning: "Uzun", level: "A2" },
    { id: 2292, word: "Look", meaning: "Bakmak", level: "A2" },
    { id: 2293, word: "Loose", meaning: "Gevşek", level: "B1" },
    { id: 2294, word: "Lord", meaning: "Efendi, Rab", level: "B2" },
    { id: 2295, word: "Lorry", meaning: "Kamyon", level: "A2" },
    { id: 2296, word: "Lose", meaning: "Kaybetmek", level: "A2" },
    { id: 2297, word: "Loss", meaning: "Kayıp", level: "B1" },
    { id: 2298, word: "Lost", meaning: "Kayıp", level: "A2" },
    { id: 2299, word: "Lot", meaning: "Çok fazla", level: "A2" },
    { id: 2300, word: "Loud", meaning: "Yüksek sesli", level: "A2" },
    { id: 2301, word: "Loudly", meaning: "Yüksek sesle", level: "A2" },
    { id: 2302, word: "Love", meaning: "Sevmek", level: "A2" },
    { id: 2303, word: "Lovely", meaning: "Sevimli, Güzel", level: "A2" },
    { id: 2304, word: "Low", meaning: "Düşük", level: "A2" },
    { id: 2305, word: "Lower", meaning: "Daha düşük, Alt", level: "B1" },
    { id: 2306, word: "Loyal", meaning: "Sadık", level: "B2" },
    { id: 2307, word: "Luck", meaning: "Şans", level: "A2" },
    { id: 2308, word: "Lucky", meaning: "Şanslı", level: "A2" },
    { id: 2309, word: "Lunch", meaning: "Öğle yemeği", level: "A2" },
    { id: 2310, word: "Lung", meaning: "Akciğer", level: "B1" },
    { id: 2311, word: "Luxury", meaning: "Lüks", level: "B1" },
    { id: 2312, word: "Machine", meaning: "Makine", level: "A2" },
    { id: 2313, word: "Mad", meaning: "Deli, Kızgın", level: "A2" },
    { id: 2314, word: "Magazine", meaning: "Dergi", level: "A2" },
    { id: 2315, word: "Magic", meaning: "Büyü, Sihir", level: "B1" },
    { id: 2316, word: "Mail", meaning: "Posta", level: "A2" },
    { id: 2317, word: "Main", meaning: "Ana", level: "A2" },
    { id: 2318, word: "Mainly", meaning: "Esas olarak", level: "B1" },
    { id: 2319, word: "Maintain", meaning: "Korumak, Sürdürmek", level: "B2" },
    { id: 2320, word: "Major", meaning: "Başlıca, Önemli", level: "B1" },
    { id: 2321, word: "Majority", meaning: "Çoğunluk", level: "B2" },
    { id: 2322, word: "Make", meaning: "Yapmak", level: "A2" },
    { id: 2323, word: "Male", meaning: "Erkek", level: "A2" },
    { id: 2324, word: "Mall", meaning: "Alışveriş merkezi", level: "A2" },
    { id: 2325, word: "Man", meaning: "Adam", level: "A2" },
    { id: 2326, word: "Manage", meaning: "Yönetmek", level: "A2" },
    { id: 2327, word: "Management", meaning: "Yönetim", level: "B1" },
    { id: 2328, word: "Manager", meaning: "Müdür", level: "A2" },
    { id: 2329, word: "Manner", meaning: "Tarz, Tavır", level: "B2" },
    { id: 2330, word: "Many", meaning: "Pek çok", level: "A2" },
    { id: 2331, word: "Map", meaning: "Harita", level: "A2" },
    { id: 2332, word: "March", meaning: "Mart", level: "A2" },
    { id: 2333, word: "Mark", meaning: "İşaret, Not", level: "A2" },
    { id: 2334, word: "Market", meaning: "Market", level: "A2" },
    { id: 2335, word: "Marketing", meaning: "Pazarlama", level: "B1" },
    { id: 2336, word: "Marriage", meaning: "Evlilik", level: "B1" },
    { id: 2337, word: "Married", meaning: "Evli", level: "A2" },
    { id: 2338, word: "Marry", meaning: "Evlenmek", level: "A2" },
    { id: 2339, word: "Mass", meaning: "Kitle", level: "B2" },
    { id: 2340, word: "Massive", meaning: "Devasa", level: "B2" },
    { id: 2341, word: "Master", meaning: "Usta, Efendi", level: "B2" },
    { id: 2342, word: "Match", meaning: "Maç, Eşleşmek", level: "A2" },
    { id: 2343, word: "Material", meaning: "Malzeme", level: "A2" },
    { id: 2344, word: "Math", meaning: "Matematik", level: "A2" },
    { id: 2345, word: "Mathematics", meaning: "Matematik", level: "A2" },
    { id: 2346, word: "Matter", meaning: "Mesele", level: "A2" },
    { id: 2347, word: "Maximum", meaning: "Maksimum", level: "B2" },
    { id: 2348, word: "May", meaning: "Mayıs", level: "A2" },
    { id: 2349, word: "Maybe", meaning: "Belki", level: "A2" },
    { id: 2350, word: "Meal", meaning: "Öğün", level: "A2" },
    { id: 2351, word: "Mean", meaning: "Anlamak, Cimri", level: "A2" },
    { id: 2352, word: "Meaning", meaning: "Anlam", level: "A2" },
    { id: 2353, word: "Means", meaning: "Araçlar", level: "B2" },
    { id: 2354, word: "Meanwhile", meaning: "Bu sırada", level: "B1" },
    { id: 2355, word: "Measure", meaning: "Ölçmek", level: "B1" },
    { id: 2356, word: "Measurement", meaning: "Ölçü", level: "B2" },
    { id: 2357, word: "Meat", meaning: "Et", level: "A2" },
    { id: 2358, word: "Mechanism", meaning: "Mekanizma", level: "B2" },
    { id: 2359, word: "Media", meaning: "Medya", level: "B1" },
    { id: 2360, word: "Medical", meaning: "Tıbbi", level: "B1" },
    { id: 2361, word: "Medicine", meaning: "İlaç", level: "A2" },
    { id: 2362, word: "Medium", meaning: "Orta", level: "B1" },
    { id: 2363, word: "Meet", meaning: "Buluşmak", level: "A2" },
    { id: 2364, word: "Meeting", meaning: "Toplantı", level: "A2" },
    { id: 2365, word: "Member", meaning: "Üye", level: "A2" },
    { id: 2366, word: "Membership", meaning: "Üyelik", level: "B1" },
    { id: 2367, word: "Memory", meaning: "Hafıza", level: "A2" },
    { id: 2368, word: "Mental", meaning: "Zihinsel", level: "B1" },
    { id: 2369, word: "Mention", meaning: "Bahsetmek", level: "B1" },
    { id: 2370, word: "Menu", meaning: "Menü", level: "A2" },
    { id: 2371, word: "Mere", meaning: "Sadece", level: "B2" },
    { id: 2372, word: "Merely", meaning: "Yalnızca", level: "B2" },
    { id: 2373, word: "Message", meaning: "Mesaj", level: "A2" },
    { id: 2374, word: "Metal", meaning: "Metal", level: "A2" },
    { id: 2375, word: "Method", meaning: "Yöntem", level: "A2" },
    { id: 2376, word: "Metre", meaning: "Metre", level: "A2" },
    { id: 2377, word: "Middle", meaning: "Orta", level: "A2" },
    { id: 2378, word: "Midnight", meaning: "Gece yarısı", level: "A2" },
    { id: 2379, word: "Might", meaning: "-bilir (İhtimal)", level: "A2" },
    { id: 2380, word: "Mild", meaning: "Ilıman", level: "B1" },
    { id: 2381, word: "Mile", meaning: "Mil", level: "A2" },
    { id: 2382, word: "Military", meaning: "Askeri", level: "B1" },
    { id: 2383, word: "Milk", meaning: "Süt", level: "A2" },
    { id: 2384, word: "Million", meaning: "Milyon", level: "A2" },
    { id: 2385, word: "Mind", meaning: "Zihin, Akıl", level: "A2" },
    { id: 2386, word: "Mine", meaning: "Benimki", level: "A2" },
    { id: 2387, word: "Mineral", meaning: "Mineral", level: "B1" },
    { id: 2388, word: "Minister", meaning: "Bakan", level: "B1" },
    { id: 2389, word: "Minor", meaning: "Küçük, Önemsiz", level: "B2" },
    { id: 2390, word: "Minority", meaning: "Azınlık", level: "B2" },
    { id: 2391, word: "Minute", meaning: "Dakika", level: "A2" },
    { id: 2392, word: "Mirror", meaning: "Ayna", level: "A2" },
    { id: 2393, word: "Miss", meaning: "Özlemek, Kaçırmak", level: "A2" },
    { id: 2394, word: "Missing", meaning: "Eksik", level: "A2" },
    { id: 2395, word: "Mission", meaning: "Görev", level: "B1" },
    { id: 2396, word: "Mistake", meaning: "Hata", level: "A2" },
    { id: 2397, word: "Mix", meaning: "Karıştırmak", level: "B1" },
    { id: 2398, word: "Mixed", meaning: "Karışık", level: "B1" },
    { id: 2399, word: "Mixture", meaning: "Karışım", level: "B2" },
    { id: 2400, word: "Mobile", meaning: "Mobil", level: "A2" },
    { id: 2401, word: "Model", meaning: "Model", level: "A2" },
    { id: 2402, word: "Modern", meaning: "Modern", level: "A2" },
    { id: 2403, word: "Moment", meaning: "An", level: "A2" },
    { id: 2404, word: "Monday", meaning: "Pazartesi", level: "A2" },
    { id: 2405, word: "Money", meaning: "Para", level: "A2" },
    { id: 2406, word: "Monitor", meaning: "İzlemek, Monitör", level: "B1" },
    { id: 2407, word: "Month", meaning: "Ay", level: "A2" },
    { id: 2408, word: "Mood", meaning: "Mod, Ruh hali", level: "B1" },
    { id: 2409, word: "Moon", meaning: "Ay (Gökyüzü)", level: "A2" },
    { id: 2410, word: "Moral", meaning: "Ahlaki", level: "B2" },
    { id: 2411, word: "More", meaning: "Daha fazla", level: "A2" },
    { id: 2412, word: "Moreover", meaning: "Ayrıca", level: "B2" },
    { id: 2413, word: "Morning", meaning: "Sabah", level: "A2" },
    { id: 2414, word: "Most", meaning: "En çok", level: "A2" },
    { id: 2415, word: "Mostly", meaning: "Çoğunlukla", level: "A2" },
    { id: 2416, word: "Mother", meaning: "Anne", level: "A2" },
    { id: 2417, word: "Motion", meaning: "Hareket", level: "B1" },
    { id: 2418, word: "Motivation", meaning: "Motivasyon", level: "B2" },
    { id: 2419, word: "Motor", meaning: "Motor", level: "A2" },
    { id: 2420, word: "Mountain", meaning: "Dağ", level: "A2" },
    { id: 2421, word: "Mouse", meaning: "Fare", level: "A2" },
    { id: 2422, word: "Mouth", meaning: "Ağız", level: "A2" },
    { id: 2423, word: "Move", meaning: "Hareket etmek, Taşınmak", level: "A2" },
    { id: 2424, word: "Movement", meaning: "Hareket", level: "A2" },
    { id: 2425, word: "Movie", meaning: "Film", level: "A2" },
    { id: 2426, word: "Much", meaning: "Çok", level: "A2" },
    { id: 2427, word: "Mud", meaning: "Çamur", level: "B1" },
    { id: 2428, word: "Multiple", meaning: "Çoklu", level: "B1" },
    { id: 2429, word: "Multiply", meaning: "Çarpmak", level: "B1" },
    { id: 2430, word: "Murder", meaning: "Cinayet", level: "B1" },
    { id: 2431, word: "Muscle", meaning: "Kas", level: "B1" },
    { id: 2432, word: "Museum", meaning: "Müze", level: "A2" },
    { id: 2433, word: "Music", meaning: "Müzik", level: "A2" },
    { id: 2434, word: "Musical", meaning: "Müzikal", level: "A2" },
    { id: 2435, word: "Musician", meaning: "Müzisyen", level: "A2" },
    { id: 2436, word: "Must", meaning: "-meli, -malı", level: "A2" },
    { id: 2437, word: "My", meaning: "Benim", level: "A2" },
    { id: 2438, word: "Myself", meaning: "Kendim", level: "A2" },
    { id: 2439, word: "Mysterious", meaning: "Gizemli", level: "B1" },
    { id: 2440, word: "Mystery", meaning: "Gizem", level: "B1" },
    { id: 2441, word: "Nail", meaning: "Tırnak, Çivi", level: "B1" },
    { id: 2442, word: "Name", meaning: "İsim", level: "A2" },
    { id: 2443, word: "Narrow", meaning: "Dar", level: "B1" },
    { id: 2444, word: "Nation", meaning: "Ulus", level: "B1" },
    { id: 2445, word: "National", meaning: "Ulusal", level: "B1" },
    { id: 2446, word: "Native", meaning: "Yerli", level: "B2" },
    { id: 2447, word: "Natural", meaning: "Doğal", level: "A2" },
    { id: 2448, word: "Naturally", meaning: "Doğal olarak", level: "B1" },
    { id: 2449, word: "Nature", meaning: "Doğa", level: "A2" },
    { id: 2450, word: "Near", meaning: "Yakın", level: "A2" },
    { id: 2451, word: "Nearby", meaning: "Yakınlarda", level: "A2" },
    { id: 2452, word: "Nearly", meaning: "Neredeyse", level: "A2" },
    { id: 2453, word: "Neat", meaning: "Düzenli", level: "B2" },
    { id: 2454, word: "Necessary", meaning: "Gerekli", level: "A2" },
    { id: 2455, word: "Neck", meaning: "Boyun", level: "A2" },
    { id: 2456, word: "Need", meaning: "İhtiyaç duymak", level: "A2" },
    { id: 2457, word: "Needle", meaning: "İğne", level: "B1" },
    { id: 2458, word: "Negative", meaning: "Negatif", level: "A2" },
    { id: 2459, word: "Neighbour", meaning: "Komşu", level: "A2" },
    { id: 2460, word: "Neighborhood", meaning: "Mahalle", level: "B1" },
    { id: 2461, word: "Neither", meaning: "Ne ... ne de", level: "B1" },
    { id: 2462, word: "Nerve", meaning: "Sinir", level: "B1" },
    { id: 2463, word: "Nervous", meaning: "Gergin", level: "A2" },
    { id: 2464, word: "Nest", meaning: "Yuva", level: "B1" },
    { id: 2465, word: "Net", meaning: "Ağ, Net", level: "B1" },
    { id: 2466, word: "Network", meaning: "Ağ", level: "B1" },
    { id: 2467, word: "Never", meaning: "Asla", level: "A2" },
    { id: 2468, word: "Nevertheless", meaning: "Yine de", level: "B2" },
    { id: 2469, word: "New", meaning: "Yeni", level: "A2" },
    { id: 2470, word: "Newly", meaning: "Yeni", level: "B2" },
    { id: 2471, word: "News", meaning: "Haberler", level: "A2" },
    { id: 2472, word: "Newspaper", meaning: "Gazete", level: "A2" },
    { id: 2473, word: "Next", meaning: "Gelecek, Sonraki", level: "A2" },
    { id: 2474, word: "Nice", meaning: "Hoş", level: "A2" },
    { id: 2475, word: "Night", meaning: "Gece", level: "A2" },
    { id: 2476, word: "Nine", meaning: "Dokuz", level: "A2" },
    { id: 2477, word: "Nineteen", meaning: "On dokuz", level: "A2" },
    { id: 2478, word: "Ninety", meaning: "Doksan", level: "A2" },
    { id: 2479, word: "No", meaning: "Hayır", level: "A2" },
    { id: 2480, word: "Nobody", meaning: "Hiç kimse", level: "A2" },
    { id: 2481, word: "Noise", meaning: "Gürültü", level: "A2" },
    { id: 2482, word: "Noisy", meaning: "Gürültülü", level: "A2" },
    { id: 2483, word: "None", meaning: "Hiçbiri", level: "B1" },
    { id: 2484, word: "Normal", meaning: "Normal", level: "A2" },
    { id: 2485, word: "Normally", meaning: "Normalde", level: "A2" },
    { id: 2486, word: "North", meaning: "Kuzey", level: "A2" },
    { id: 2487, word: "Northern", meaning: "Kuzeyli", level: "B1" },
    { id: 2488, word: "Nose", meaning: "Burun", level: "A2" },
    { id: 2489, word: "Not", meaning: "Değil", level: "A2" },
    { id: 2490, word: "Note", meaning: "Not", level: "A2" },
    { id: 2491, word: "Nothing", meaning: "Hiçbir şey", level: "A2" },
    { id: 2492, word: "Notice", meaning: "Fark etmek, İlan", level: "A2" },
    { id: 2493, word: "Novel", meaning: "Roman", level: "A2" },
    { id: 2494, word: "November", meaning: "Kasım", level: "A2" },
    { id: 2495, word: "Now", meaning: "Şimdi", level: "A2" },
    { id: 2496, word: "Nowadays", meaning: "Bugünlerde", level: "B1" },
    { id: 2497, word: "Nuclear", meaning: "Nükleer", level: "B1" },
    { id: 2498, word: "Number", meaning: "Sayı", level: "A2" },
    { id: 2499, word: "Nurse", meaning: "Hemşire", level: "A2" },
    { id: 2500, word: "Nut", meaning: "Somun, Fındık", level: "A2" }
];
